# Node base image for build
FROM node:24-alpine
# Working directory inside the image
WORKDIR /workdir
# Copy package files to working directory
COPY package*.json .
# Install npm dependencies
RUN npm ci
# Copy source code to working directory
COPY . .
# Expose port
EXPOSE 5173
# Run
CMD ["npm", "run", "dev", "--", "--port", "5173"]