name: sanaboksi

services:
  database:
    container_name: sanaboksi_database
    image: postgres:18.1
    restart: always
    volumes:
      - data:/var/lib/postgresql
    ports:
      # Port variables are configured in .env file
      - "${DATABASE_HOST_PORT}:5432"
    networks:
      - network
    environment:
      # Environment variables are configured in .env file
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      # Environment variables are configured in .env file
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    container_name: sanaboksi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      # Port variables are configured in .env file
      - "${BACKEND_HOST_PORT}:8080"
    networks:
      - network
    environment:
      # Environment variables are configured in .env file (and passed to application.yaml)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    container_name: sanaboksi_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # Port variables are configured in .env file
      - "${FRONTEND_HOST_PORT}:80"
    networks:
      - network
    depends_on:
      backend:
        condition: service_healthy

networks:
  network:
    driver: bridge

volumes:
  data: