name: sanaboksi

services:

  backend:
    container_name: sanaboksi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network
    volumes:
      - database:/database
    environment:
      # Environment variables are configured in .env file (and passed to application.yaml)
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    container_name: sanaboksi_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          VITE_SERVER_URL: ${VITE_SERVER_URL}
    ports:
      - "5173:80"
    networks:
      - network
    depends_on:
      backend:
        condition: service_healthy

networks:
  network:
    driver: bridge

volumes:
  database: