-- Original data from Kotus (CC BY 4.0): https://kotus.fi/sanakirjat/kielitoimiston-sanakirja/nykysuomen-sana-aineistot/nykysuomen-sanalista/
-- Modified to fit this project's needs:
--      1) removed all words with fewer or more than 7 letters
--      2) removed words with diacritics (i.e. é, è, š)    
--      3) removed words ending in or including '-' (i.e. sika-)
--      4) removed derogatory words
--      5) removed words with a space in beteen (i.e. "au pair")

DELETE FROM finnish_words WHERE LENGTH(word) = 7;

-- Words starting with A
INSERT INTO finnish_words(word) VALUES
('aallota'), ('aapasuo'), ('aapinen'), ('aarpora'), ('aatella'), ('aavikko'), ('abhaasi'), ('abnormi'), ('abortti'), ('absessi'),
('absurdi'), ('addikti'), ('adoptio'), ('adressi'), ('adverbi'), ('aerobic'), ('affekti'), ('affisio'), ('afgaani'), ('agaatti'),
('agentti'), ('agility'), ('ahdinko'), ('aherrus'), ('ahertaa'), ('ahmaisu'), ('ahmatti'), ('ahminta'), ('ahtaaja'), ('ahtauma'),
('ahtojää'), ('aidanne'), ('aidosti'), ('aiemmin'), ('aiennus'), ('aientaa'), ('aihelma'), ('aikaero'), ('aikailu'), ('aikansa'),
('aikomus'), ('ailakki'), ('ainakin'), ('aineosa'), ('ainiaan'), ('airsoft'), ('aivosto'), ('aivoton'), ('aivotyö'), ('ajastaa'),
('ajastin'), ('ajastus'), ('ajattaa'), ('ajautua'), ('ajettua'), ('ajoaika'), ('ajoakku'), ('ajoissa'), ('ajoitus'), ('ajokeli'),
('ajokyky'), ('ajomies'), ('ajopeli'), ('ajoporo'), ('ajorata'), ('akaatti'), ('akantti'), ('akryyli'), ('aksepti'), ('aksiomi'),
('aktiivi'), ('akuutti'), ('aladobi'), ('alainen'), ('alakulo'), ('alalaji'), ('alamäki'), ('alaoksa'), ('alapesu'), ('alapeti'),
('alaraja'), ('alarivi'), ('alasajo'), ('alaston'), ('alavuus'), ('alaääni'), ('albaani'), ('albania'), ('albiino'), ('alemmas'),
('alempaa'), ('alenema'), ('aleneva'), ('alennus'), ('alentaa'), ('alentua'), ('aleutti'), ('alfalfa'), ('algebra'), ('alhaiso'),
('alimmas'), ('alistaa'), ('alistua'), ('alistus'), ('alittaa'), ('alittua'), ('alkuaan'), ('alkuerä'), ('alkukuu'), ('alkuosa'),
('alkupää'), ('alkusyy'), ('allakka'), ('alleeli'), ('allegro'), ('allikko'), ('aloitus'), ('alpakka'), ('altiste'), ('altisti'),
('alttari'), ('alttius'), ('alusasu'), ('alusmaa'), ('alustaa'), ('alustus'), ('ambitio'), ('ammatti'), ('ammolla'), ('ammolle'),
('ammunta'), ('amnesia'), ('ampeeri'), ('amppeli'), ('ampulla'), ('ampulli'), ('anaboli'), ('anarkia'), ('anastaa'), ('anastus'),
('anatomi'), ('andante'), ('angervo'), ('angiina'), ('aniitti'), ('anjovis'), ('ankkuri'), ('annatto'), ('annella'), ('annoona'),
('ansaita'), ('ansatsi'), ('antabus'), ('antenni'), ('antimet'), ('antoisa'), ('apeasti'), ('apekset'), ('apeutua'), ('apposen'),
('apposet'), ('aprilli'), ('apropoo'), ('apuaine'), ('apumies'), ('apuraha'), ('apusana'), ('aputaso'), ('arastaa'), ('arbuusi'),
('aristaa'), ('aristua'), ('aristus'), ('arkeoni'), ('arkinen'), ('arkisin'), ('arkisto'), ('armeija'), ('armoton'), ('aropupu'),
('arpeuma'), ('arpinen'), ('arrakki'), ('arseeni'), ('arteria'), ('artikla'), ('artisti'), ('arvailu'), ('arvella'), ('arvoisa'),
('arvokas'), ('arvonta'), ('arvopuu'), ('arvoton'), ('asbesti'), ('aseeton'), ('aselaji'), ('aselepo'), ('aselupa'), ('asemies'),
('asennus'), ('asentaa'), ('asentua'), ('asepaja'), ('asepuku'), ('asetoni'), ('asettaa'), ('asettua'), ('aseveli'), ('asiakas'),
('asiaton'), ('asioida'), ('askeesi'), ('askelma'), ('askites'), ('aspekti'), ('astella'), ('astenia'), ('astunta'), ('astutus'),
('asujain'), ('asustaa'), ('asuttaa'), ('ateismi'), ('ateisti'), ('ateljee'), ('atrofia'), ('atropia'), ('atsalea'), ('attasea'),
('aukaisu'), ('aukeama'), ('aukiolo'), ('aukoton'), ('aukotus'), ('aurinko'), ('autella'), ('autismi'), ('autoetu'), ('autoilu'), 
('autoton'), ('auttaja'), ('auttava'), ('auvoisa'), ('avarrin'), ('avarrus'), ('avartaa'), ('avartua'), ('avaruus'), ('avautua'), 
('aversio'), ('avioero'), ('avioton'), ('avittaa'), ('avoauto'), ('avoinna'), ('avojono'), ('avokado'), ('avolava'), ('avomeri'), 
('avomies'), ('avopari'), ('avopäin'), ('avorivi'), ('avosuin'), ('avotavu'), ('avotila'), ('avotuli'), ('avovene'), ('avovesi'), 
('avulias'), ('avustaa'), ('avustus');

-- Words starting with B
INSERT INTO finnish_words(word) VALUES
('bailata'), ('bailaus'), ('baklava'), ('baletti'), ('balladi'), ('balonki'), ('balsami'), ('banaali'), ('banaani'), ('banneri'), 
('baretti'), ('barista'), ('barokki'), ('barreli'), ('basaari'), ('basenji'), ('basilli'), ('basisti'), ('baskeri'), ('batikki'), 
('batisti'), ('beatbox'), ('begonia'), ('beguine'), ('beignet'), ('benigni'), ('berberi'), ('berylli'), ('bestman'), ('bigamia'), 
('bigband'), ('biisami'), ('biisoni'), ('bikinit'), ('biletys'), ('bingota'), ('biojäte'), ('biologi'), ('biopsia'), ('biouhka'), 
('bisarri'), ('bitcoin'), ('blandis'), ('blogata'), ('blokata'), ('bodaaja'), ('boheemi'), ('boileri'), ('bokseri'), ('bongari'), 
('bongata'), ('bongaus'), ('boomeri'), ('bouquet'), ('bourbon'), ('breikki'), ('brenkku'), ('briiffi'), ('briossi'), ('broisku'), 
('brokadi'), ('brosari'), ('brownie'), ('brunssi'), ('bufetti'), ('bulguri'), ('bulimia'), ('burgeri'), ('burkini'), ('burnout'), 
('burrito'), ('butaani'), ('buukata'), ('buumeri'), ('buutata'), ('bäkkäri'), ('bänksit');

-- Words starting with C
INSERT INTO finnish_words(word) VALUES
('calypso'), ('camping'), ('canasta'), ('catwalk'), ('cembalo'), ('ceviche'), ('chanson'), ('chapati'), ('chatata'), ('cheddar'), 
('chianti'), ('chorizo'), ('chutney'), ('college'), ('cosplay'), ('country'), ('cumulus'), ('curling');

-- Words starting with D
INSERT INTO finnish_words(word) VALUES
('damaski'), ('damasti'), ('datiivi'), ('debatti'), ('debiili'), ('defekti'), ('deitata'), ('dekaani'), ('dekkari'), ('detalji'), 
('diaario'), ('diakoni'), ('diakuva'), ('dialogi'), ('dieetti'), ('diileri'), ('diivata'), ('dilemma'), ('dinaari'), ('diplomi'), 
('dippaus'), ('dirhami'), ('diskata'), ('diskaus'), ('diskota'), ('dissata'), ('divaani'), ('dokkari'), ('dollari'), ('dominio'), 
('donitsi'), ('donjuan'), ('donkata'), ('dosetti'), ('doupata'), ('drinkki'), ('drinksu'), ('dubbaus'), ('duffeli'), ('dumpata'), 
('dumping'), ('duopoli'), ('duunari'), ('duunata'), ('duunaus'), ('dyykata');

-- Words starting with E
INSERT INTO finnish_words(word) VALUES
('edeltää'), ('edemmäs'), ('edempää'), ('edistys'), ('edistyä'), ('edistää'), ('editori'), ('edustaa'), ('edustua'), ('edustus'),
('eekkeri'), ('eepikko'), ('eespäin'), ('eestaas'), ('eetteri'), ('egoismi'), ('egoisti'), ('ehdokas'), ('ehdoton'), ('ehdotus'),
('eheytys'), ('eheytyä'), ('eheästi'), ('ehjästi'), ('ehkäisy'), ('ehommin'), ('ehostaa'), ('ehostus'), ('ehtoisa'), ('ehättää'),
('eilinen'), ('ekologi'), ('ekonomi'), ('ekotalo'), ('ekotase'), ('eksakti'), ('ekseema'), ('eksykki'), ('eksymys'), ('eksytys'),
('eleetön'), ('elehtiä'), ('eliitti'), ('eliöstö'), ('ellipsi'), ('ellotus'), ('elokehä'), ('elokuva'), ('elostua'), ('elotuli'),
('elvytys'), ('eläköön'), ('elättää'), ('elävyys'), ('eläymys'), ('eläytyä'), ('embargo'), ('emerita'), ('emissio'), ('emoalus'),
('emokala'), ('emolevy'), ('emootio'), ('emosolu'), ('empatia'), ('empiiri'), ('empiria'), ('emulsio'), ('emäalus'), ('emäjoki'),
('emäsika'), ('emätila'), ('endiivi'), ('enemmän'), ('enempää'), ('enenevä'), ('enennys'), ('enentyä'), ('enentää'), ('energia'),
('enimmin'), ('enimmän'), ('ennakko'), ('ennalta'), ('enneuni'), ('ennuste'), ('ennätys'), ('enologi'), ('ensiapu'), ('ensikko'),
('ensiksi'), ('ensinnä'), ('enteily'), ('entinen'), ('entrata'), ('entraus'), ('entäpäs'), ('epiikka'), ('epilogi'), ('episodi'),
('epookki'), ('epsilon'), ('epäaito'), ('epäillä'), ('epäilty'), ('epäilys'), ('epäjalo'), ('epäonni'), ('epäpyhä'), ('epäsopu'),
('epätosi'), ('epäusko'), ('erehdys'), ('erehtyä'), ('erektio'), ('eripura'), ('eristin'), ('eristys'), ('eristyä'), ('eristää'),
('erittyä'), ('erittää'), ('eriytys'), ('eriytyä'), ('erkanee'), ('erkauma'), ('erkkeri'), ('eroosio'), ('eroraha'), ('erosija'),
('erottaa'), ('erottua'), ('eräalue'), ('eräluku'), ('erämies'), ('eräopas'), ('esanssi'), ('esiaste'), ('esikuva'), ('esimaku'),
('esimies'), ('esipesu'), ('esipiha'), ('esipuhe'), ('esittää'), ('esiäiti'), ('espanja'), ('essiivi'), ('estellä'), ('estoton'),
('estradi'), ('etanoli'), ('eteinen'), ('etemmäs'), ('etempää'), ('etenemä'), ('etenijä'), ('etenkin'), ('etevyys'), ('etiikka'),
('etninen'), ('etruski'), ('etsaaja'), ('etsikko'), ('etsintä'), ('etteikö'), ('ettonen'), ('etuanti'), ('etuhele'), ('etuilla'),
('etumies'), ('etunimi'), ('etunoja'), ('etupesä'), ('eturivi'), ('etusija'), ('etusivu'), ('etuvalo'), ('etuveto'), ('etäinen'),
('etäpeli'), ('etäälle'), ('etäällä'), ('etäältä'), ('euforia'), ('eunukki'), ('euribor'), ('euromaa'), ('eversti'), ('evästys'),
('evästää');

-- Words starting with F
INSERT INTO finnish_words(word) VALUES
('faabeli'), ('fagotti'), ('fakiiri'), ('faksata'), ('faksaus'), ('faktori'), ('falafel'), ('falangi'), ('faneeri'), ('farmari'), 
('fasaani'), ('fasismi'), ('fasisti'), ('fataali'), ('fatbike'), ('feature'), ('feeniks'), ('feidata'), ('feikata'), ('feilata'), 
('fenkoli'), ('festari'), ('fetissi'), ('fiftari'), ('figuuri'), ('fiiberi'), ('fikkari'), ('fiksata'), ('fiksuus'), ('filetti'),
('fillari'), ('filmata'), ('filmaus'), ('filunki'), ('fimoosi'), ('finaali'), ('finessi'), ('fisteli'), ('fitness'), ('flirtti'),
('flopata'), ('flunssa'), ('fondant'), ('foneemi'), ('foorumi'), ('forelli'), ('formula'), ('fortuna'), ('fosfori'), ('foxtrot'),
('fraktio'), ('frankki'), ('freesia'), ('frigidi'), ('friikki'), ('frisbee'), ('fruitie'), ('funkkis'), ('funktio'), ('funtsia'),
('fusilli'), ('fuskata'), ('fuskaus'), ('futaaja'), ('futuuri'), ('fyssari'), ('föönata'), ('föönaus');

-- Words starting with G
INSERT INTO finnish_words(word) VALUES
('galaksi'), ('galanga'), ('gallona'), ('ganglio'), ('gaselli'), ('genever'), ('geologi'), ('gepardi'), ('gerbera'), ('gibboni'), 
('glamour'), ('glooria'), ('glykoli'), ('gneissi'), ('gnocchi'), ('golfata'), ('gondoli'), ('gorilla'), ('gourmee'), ('gourmet'), 
('granita'), ('granola'), ('gravidi'), ('greippi'), ('griippi'), ('guarana'), ('gulassi'), ('guldeni');

-- Words starting with H
INSERT INTO finnish_words(word) VALUES
('haalari'), ('haalata'), ('haaleta'), ('haaleus'), ('haaltua'), ('haapana'), ('haarake'), ('haaremi'), ('haaskio'), ('haaskuu'),
('haastaa'), ('haaveri'), ('haavuri'), ('habitus'), ('hadroni'), ('haettaa'), ('hahtuva'), ('haihtua'), ('haikala'), ('haikara'),
('haikeus'), ('haistaa'), ('haisuli'), ('haitari'), ('haitata'), ('haituva'), ('hajalla'), ('hajalle'), ('hajauma'), ('hajonta'),
('hajotus'), ('hajuste'), ('hajuton'), ('hakamaa'), ('hakanen'), ('hakemus'), ('hakepuu'), ('haketin'), ('haketus'), ('hakkaus'),
('hakkeri'), ('hakkuri'), ('halailu'), ('halatti'), ('haljeta'), ('hallava'), ('hallayö'), ('hallita'), ('halpuus'), ('haltija'),
('haltuun'), ('halukas'), ('haluton'), ('haluttu'), ('halvata'), ('halvaus'), ('halveta'), ('hamassa'), ('hamasta'), ('hamonen'),
('hampsia'), ('hanakka'), ('handout'), ('hangata'), ('hangota'), ('hanikka'), ('hankain'), ('hankala'), ('hankaus'), ('hankkia'),
('hanukka'), ('hapatin'), ('hapatus'), ('hapekas'), ('hapetin'), ('hapetus'), ('hapokas'), ('hapotus'), ('hapuilu'), ('harakka'),
('haralla'), ('haralle'), ('harhaan'), ('harhama'), ('harilla'), ('harille'), ('haritus'), ('harjake'), ('harjata'), ('harjaus'),
('harjava'), ('harkita'), ('harmaus'), ('harmeta'), ('harmoni'), ('harpata'), ('harppia'), ('harppoa'), ('hartaus'), ('harteet'),
('harteva'), ('harvaan'), ('harveta'), ('harvoin'), ('harvuus'), ('hasardi'), ('hashtag'), ('hassata'), ('hatikka'), ('hattara'),
('haudata'), ('hauduke'), ('haudute'), ('haukata'), ('haukkoa'), ('haukkua'), ('hauraus'), ('haureus'), ('hautaus'), ('hautomo'),
('hautuma'), ('hauturi'), ('hauveli'), ('havaita'), ('havista'), ('havupuu'), ('havutus'), ('hedelmä'), ('hehkeys'), ('heijari'),
('heijata'), ('heiketä'), ('heikota'), ('heilaus'), ('heiluri'), ('heimous'), ('heinätä'), ('heinäys'), ('heittiö'), ('heittyä'),
('heittää'), ('heivata'), ('hekotus'), ('helakka'), ('helapää'), ('helibor'), ('helistä'), ('helkkyä'), ('hellitä'), ('hellyys'),
('hellätä'), ('helokki'), ('helotus'), ('helpota'), ('helskyä'), ('helskää'), ('heläjää'), ('hempeys'), ('hengata'), ('henkari'),
('henkevä'), ('henkiin'), ('henkilö'), ('henkäys'), ('hennata'), ('hentous'), ('herjata'), ('herjaus'), ('herjetä'), ('herketä'),
('herkkis'), ('herraus'), ('herruus'), ('herttua'), ('herukka'), ('herutus'), ('hervota'), ('herätys'), ('heräämö'), ('hetaira'),
('hevillä'), ('hevonen'), ('hidalgo'), ('hidaste'), ('hienota'), ('hienous'), ('hieroja'), ('hierrin'), ('hiertyä'), ('hiertää'),
('hiestyä'), ('hiestää'), ('hiffata'), ('hihaton'), ('hihhuli'), ('hihitys'), ('hiihdin'), ('hiihtää'), ('hiilari'), ('hiillos'),
('hiiltyä'), ('hiiltää'), ('hiipata'), ('hiipivä'), ('hiiskua'), ('hiitata'), ('hiiteen'), ('hiivata'), ('hikinen'), ('hikkori'),
('hikoilu'), ('hiljetä'), ('hilleri'), ('hillitä'), ('hilloke'), ('hillota'), ('hilpari'), ('hilpeys'), ('himmeli'), ('himmetä'),
('himmeys'), ('himoita'), ('himokas'), ('hinaaja'), ('hinkalo'), ('hinkata'), ('hintava'), ('hintelä'), ('hiostaa'), ('hiostua'),
('hiostus'), ('hiottaa'), ('hioutua'), ('hipaisu'), ('hiplata'), ('hirttyä'), ('hirttää'), ('hirvetä'), ('hirveys'), ('hirvitä'),
('hissata'), ('hitailu'), ('hitosti'), ('hitsari'), ('hitsata'), ('hitsaus'), ('hitunen'), ('hiutale'), ('hiutuma'), ('hivellä'),
('hivutus'), ('hohkata'), ('hohotus'), ('hoiketa'), ('hoilata'), ('hoippua'), ('hoitaja'), ('hoitelu'), ('hoitola'), ('hoituri'),
('hoivata'), ('hoivaus'), ('hokkari'), ('hoksata'), ('holhota'), ('holhous'), ('holismi'), ('holisti'), ('holiton'), ('holkeri'),
('holvata'), ('holvaus'), ('hommata'), ('hommeli'), ('honotus'), ('hontelo'), ('hoonata'), ('hoonaus'), ('hoosata'), ('hoosaus'),
('hop hop'), ('hoppari'), ('horisko'), ('horista'), ('horjuva'), ('hormoni'), ('hotaisu'), ('hotelli'), ('houkkio'), ('houkute'),
('hourula'), ('huhmare'), ('huhuilu'), ('hui hai'), ('huijari'), ('huijata'), ('huijaus'), ('huikata'), ('huilata'), ('huimata'),
('huimaus'), ('huimeta'), ('huipata'), ('huipeta'), ('huiskaa'), ('huiskea'), ('huiskia'), ('huiskis'), ('huitsin'), ('hujoppi'),
('hukassa'), ('hukkaan'), ('hulluus'), ('hulmuta'), ('hulpilo'), ('hulppea'), ('hulttio'), ('humaani'), ('humista'), ('hummata'),
('hummaus'), ('hummeri'), ('humpata'), ('huojeta'), ('huokaus'), ('huokeus'), ('huoleti'), ('huolita'), ('huoltaa'), ('huomaan'),
('huomata'), ('huoneke'), ('huonota'), ('huonous'), ('huopaus'), ('huorata'), ('huoruus'), ('huounta'), ('huovata'), ('hupailu'),
('hupaisa'), ('hupakko'), ('huppari'), ('huppeli'), ('hupsuus'), ('huputus'), ('hurista'), ('hurjeta'), ('hurjuus'), ('hurmata'),
('hurmaus'), ('hurmuri'), ('hurrata'), ('hurskas'), ('husaari'), ('hutikka'), ('hutilus'), ('huuhtoa'), ('huullos'), ('huultaa'),
('huumata'), ('huumaus'), ('huumori'), ('huurtaa'), ('huurtua'), ('huuruta'), ('huutaja'), ('huutava'), ('huutelu'), ('huvitus'),
('hybridi'), ('hyljätä'), ('hylkäys'), ('hymistä'), ('hymyily'), ('hypellä'), ('hypetys'), ('hyppely'), ('hyppyri'), ('hyppäys'),
('hyristä'), ('hyrrätä'), ('hyrskiä'), ('hyräily'), ('hytistä'), ('hyvitys'), ('hyväily'), ('hyväkäs'), ('hyvänen'), ('hyvänsä'),
('hyvästi'), ('hyydyke'), ('hyydyte'), ('hyysätä'), ('hyytelö'), ('hyytymä'), ('hyödyke'), ('hyökätä'), ('hyörinä'), ('hyötämö'),
('hähätys'), ('häijyys'), ('häilyvä'), ('häipymä'), ('häipätä'), ('häiritä'), ('häkkyrä'), ('hälistä'), ('hälvetä'), ('hälyisä'),
('hälytin'), ('hälytys'), ('hämyisä'), ('häntyri'), ('häpyluu'), ('häpäisy'), ('härkylä'), ('härnätä'), ('härnäys'), ('härpäke'),
('härveli'), ('härvätä'), ('häröily'), ('häslätä'), ('hätäapu'), ('hätäily'), ('hätätyö'), ('hävikki'), ('hävitys'), ('häviäjä'),
('hävytön'), ('hääitku'), ('hääkuva'), ('häälyvä'), ('hääpari'), ('hääpuhe'), ('hääpuku'), ('häärinä'), ('häärätä'), ('häätalo'),
('häätapa'), ('hääväki'), ('hökkeli'), ('hökötys'), ('hölistä'), ('hölkätä'), ('hölletä'), ('höllyys'), ('höllätä'), ('höllään'),
('hölmöys'), ('hölskyä'), ('hölösuu'), ('hönkäys'), ('höpistä'), ('höppänä'), ('höpötys'), ('hörhelö'), ('hörppiä'), ('hörpätä'),
('hörölle'), ('höröllä'), ('hörössä'), ('hörötys'), ('hösseli'), ('hötäkkä'), ('höylätä'), ('höyläys'), ('höyrytä'), ('höystää'),
('höytyvä'), ('höytäle'), ('höösätä'), ('höösäys');

-- Words starting with I
INSERT INTO finnish_words(word) VALUES
('ideaali'), ('idemmäs'), ('idempää'), ('ideoida'), ('idättää'), ('ihailla'), ('ihanuus'), ('ihastua'), ('ihastus'), ('ihkasen'),
('ihmemaa'), ('ihmetys'), ('ihmetyö'), ('ihminen'), ('ihomato'), ('iisisti'), ('iisoppi'), ('ikebana'), ('ikiaika'), ('ikihyvä'),
('ikuinen'), ('ikäinen'), ('ikäkulu'), ('ikälisä'), ('ikämies'), ('ikänäkö'), ('ikäraja'), ('ikävyys'), ('ilahtua'), ('iljanko'),
('iljanne'), ('iljetys'), ('ilkeily'), ('ilkimys'), ('ilkityö'), ('ilkosen'), ('illakko'), ('ilmailu'), ('ilmaisu'), ('ilmaste'),
('ilmasto'), ('ilmaton'), ('ilmeily'), ('ilmetty'), ('ilmiasu'), ('iloinen'), ('ilostua'), ('ilotalo'), ('iltanen'), ('iltatee'),
('iltatyö'), ('ilveily'), ('imaista'), ('imeksiä'), ('imellys'), ('imeltyä'), ('imeltää'), ('imelyys'), ('imettää'), ('imeytys'),
('imeytyä'), ('immuuni'), ('imppaus'), ('improta'), ('imukyky'), ('imumato'), ('imusolu'), ('inahdus'), ('inahtaa'), ('indeksi'),
('indiisi'), ('indisio'), ('inertia'), ('inertti'), ('inhasti'), ('inhokki'), ('inhotus'), ('inkkari'), ('innoite'), ('innokas'),
('innoton'), ('insatsi'), ('insesti'), ('intiimi'), ('intoilu'), ('intrigi'), ('inuitti'), ('iridium'), ('irkkaus'), ('irrotus'),
('irstaus'), ('irtauma'), ('irtomaa'), ('irvailu'), ('irvessä'), ('irvissä'), ('irvokas'), ('iskelmä'), ('iskentä'), ('iskuala'),
('iskupää'), ('islanti'), ('isoinen'), ('isojako'), ('isontaa'), ('isontua'), ('isosetä'), ('isotäti'), ('isoveli'), ('isoviha'),
('isoäiti'), ('istukas'), ('istukka'), ('istunta'), ('istunto'), ('istutus'), ('isänisä'), ('isänmaa'), ('isäukko'), ('itaruus'),
('itiöemä'), ('itseiva'), ('itsekäs'), ('iturata'), ('itusolu'), ('itäauto'), ('itäinen'), ('itämaat'), ('itäraja'), ('itävyys'),
('ivahymy'), ('ivailla'), ('iäisyys'), ('iäkkyys');

-- Words starting with J
INSERT INTO finnish_words(word) VALUES
('jaanata'), ('jahdata'), ('jahkata'), ('jahnata'), ('jakardi'), ('jakauma'), ('jakelin'), ('jakkara'), ('jakopää'), ('jalkava'),
('jalkine'), ('jalopuu'), ('jaloste'), ('jalusta'), ('jamassa'), ('jammata'), ('jankata'), ('jaottaa'), ('jasmike'), ('jatkaja'),
('jatkumo'), ('jatkuva'), ('jatsari'), ('jazzari'), ('jeesata'), ('jeeveli'), ('jellona'), ('jelpata'), ('jelppiä'), ('jemmata'),
('jet lag'), ('jet set'), ('jiirata'), ('jobbari'), ('jodlata'), ('jodlaus'), ('joensuu'), ('johdate'), ('johtaja'), ('johtava'),
('johtuen'), ('joikata'), ('joikaus'), ('joiunta'), ('jojoilu'), ('jokisuu'), ('jokunen'), ('jolloin'), ('jomotus'), ('jonotus'),
('joogata'), ('joriini'), ('jorista'), ('jorotus'), ('jortsut'), ('joskaan'), ('jossain'), ('jostain'), ('jotakin'), ('jouheus'),
('jouheva'), ('joukkio'), ('joukkue'), ('jouluyö'), ('joustaa'), ('joustin'), ('joutava'), ('joutsen'), ('joutuin'), ('juhlava'),
('juhlija'), ('jujutsu'), ('jukebox'), ('juksata'), ('juliste'), ('juljeta'), ('julkeus'), ('julkimo'), ('julkkis'), ('julmuri'),
('julmuus'), ('jumissa'), ('jumpata'), ('juniori'), ('junnata'), ('juntata'), ('juoheus'), ('juoheva'), ('juohtua'), ('juomari'),
('juontaa'), ('juontua'), ('juoruta'), ('juotava'), ('juottaa'), ('jupakka'), ('jupikki'), ('jupista'), ('juppius'), ('juristi'),
('jurosti'), ('jurppia'), ('jurrata'), ('justiin'), ('jutella'), ('juttelu'), ('juukeli'), ('juupeli'), ('juureva'), ('juurtaa'),
('juurtua'), ('juuttua'), ('jyhkeys'), ('jylhetä'), ('jylhyys'), ('jylistä'), ('jyllätä'), ('jymistä'), ('jyristä'), ('jyrketä'),
('jyrrätä'), ('jyrsijä'), ('jyskinä'), ('jytistä'), ('jyvitys'), ('jyvänen'), ('jyystää'), ('jähmetä'), ('jähmeys'), ('jäkkärä'),
('jäkätys'), ('jälkeen'), ('jälleen'), ('jämäkkä'), ('jännite'), ('jännäri'), ('jännätä'), ('jäntere'), ('jäntevä'), ('jänteys'),
('jänönen'), ('jäpikkä'), ('järistä'), ('järkevä'), ('järkkyä'), ('järkäle'), ('järkätä'), ('jätepuu'), ('jäyhyys'), ('jäyketä'),
('jäystää'), ('jääaika'), ('jäädyke'), ('jääeste'), ('jäähile'), ('jäähtyä'), ('jääkeli'), ('jääkide'), ('jääkäri'), ('jäälasi'),
('jäämeri'), ('jäännös'), ('jääolot'), ('jääpala'), ('jääpato'), ('jäärata'), ('jääshow'), ('jääsumu'), ('jäätelö'), ('jäätymä'),
('jäätävä'), ('jäävesi'), ('jääviys'), ('jäävätä'), ('jötikkä');

-- Words starting with K
INSERT INTO finnish_words(word) VALUES
('kaaderi'), ('kaahari'), ('kaahata'), ('kaahaus'), ('kaakeli'), ('kaameus'), ('kaapata'), ('kaapeli'), ('kaareke'), ('kaareva'), 
('kaarros'), ('kaartaa'), ('kaartua'), ('kaasute'), ('kaataja'), ('kaavain'), ('kaavake'), ('kaavata'), ('kabaree'), ('kabbala'), 
('kadetti'), ('kadmium'), ('kadotus'), ('kahakka'), ('kahista'), ('kahlata'), ('kahlaus'), ('kahlita'), ('kahmalo'), ('kahmari'), 
('kahnaus'), ('kahvata'), ('kahvaus'), ('kahveli'), ('kahvila'), ('kaihdin'), ('kaihota'), ('kaihtaa'), ('kaiketi'), ('kaikota'), 
('kaikuva'), ('kainalo'), ('kainous'), ('kaipaus'), ('kairata'), ('kairaus'), ('kaitale'), ('kaitsea'), ('kaiunta'), ('kaiutin'), 
('kaiuton'), ('kaivaja'), ('kaivata'), ('kaivaus'), ('kaivuri'), ('kajaali'), ('kajakki'), ('kajetto'), ('kakkara'), ('kaksari'), 
('kakutus'), ('kalaasi'), ('kalaisa'), ('kalasto'), ('kalatie'), ('kalatäi'), ('kaldera'), ('kaleeri'), ('kalikka'), ('kalista'), 
('kaljama'), ('kaljuus'), ('kalkita'), ('kalkkaa'), ('kalkkis'), ('kalleus'), ('kalmari'), ('kalopsi'), ('kalossi'), ('kalotti'), 
('kalpeus'), ('kalppia'), ('kalseus'), ('kalsium'), ('kaltata'), ('kalteva'), ('kaltoin'), ('kaluste'), ('kalusto'), ('kaluuna'), 
('kalveta'), ('kamelia'), ('kamferi'), ('kamiina'), ('kammari'), ('kammata'), ('kammeta'), ('kammota'), ('kampata'), ('kampaus'), 
('kampela'), ('kampsut'), ('kampura'), ('kanaali'), ('kanaemo'), ('kanalja'), ('kanapee'), ('kandela'), ('kanerva'), ('kangeta'), 
('kaniini'), ('kanjoni'), ('kankare'), ('kankeus'), ('kankuri'), ('kannake'), ('kannate'), ('kannike'), ('kanslia'), ('kantaan'), 
('kantaja'), ('kantama'), ('kantata'), ('kantele'), ('kantelu'), ('kantoni'), ('kanukka'), ('kanukki'), ('kanuuna'), ('kanyyli'), 
('kapakka'), ('kapinen'), ('kapokki'), ('kappale'), ('kappeli'), ('kapseli'), ('kapusta'), ('karahka'), ('karahvi'), ('karaisu'), 
('karaoke'), ('karbidi'), ('kardoni'), ('kareilu'), ('karheta'), ('karheus'), ('karhita'), ('karhuta'), ('karikko'), ('karinen'), 
('karisma'), ('karista'), ('kariste'), ('karitsa'), ('karjala'), ('karjeta'), ('karkaus'), ('karkelo'), ('karkeus'), ('karkota'), 
('karkote'), ('karkuri'), ('karkuun'), ('karmeus'), ('karmiva'), ('karpalo'), ('karpata'), ('karsaus'), ('karsija'), ('karsina'), 
('kartano'), ('karting'), ('karttaa'), ('karttua'), ('karukko'), ('karussa'), ('karusti'), ('karvari'), ('karvata'), ('karvaus'), 
('kasakka'), ('kasarmi'), ('kasauma'), ('kasetti'), ('kashmir'), ('kasketa'), ('kasleri'), ('kassara'), ('kassari'), ('kassava'),
('kassler'), ('kastelu'), ('kastike'), ('kasukka'), ('kasuuni'), ('kasvain'), ('katarri'), ('katetri'), ('kationi'), ('katiska'),
('katkera'), ('katkero'), ('katketa'), ('katkoja'), ('katkola'), ('katoava'), ('katsaus'), ('katselu'), ('katsoja'), ('katsoma'),
('katsomo'), ('kattara'), ('kattaus'), ('kattava'), ('kattila'), ('katumus'), ('katuoja'), ('katuovi'), ('katutyö'), ('kauaksi'),
('kauemma'), ('kauempi'), ('kauheus'), ('kauhtua'), ('kauimma'), ('kaukalo'), ('kaukana'), ('kaulain'), ('kaulata'), ('kaulaus'),
('kaulita'), ('kauluri'), ('kauneus'), ('kaupata'), ('kaupita'), ('kauppis'), ('kefiiri'), ('kehaisu'), ('kehdata'), ('kehikko'),
('kehitin'), ('kehitys'), ('kehjetä'), ('kehnota'), ('kehnous'), ('kehnätä'), ('kehotus'), ('kehrätä'), ('kehräys'), ('kehunta'),
('kehveli'), ('kehyste'), ('kehätie'), ('keikari'), ('keikaus'), ('keikkua'), ('keilata'), ('keilaus'), ('keisari'), ('keittiö'),
('keittyä'), ('keittää'), ('kekkale'), ('kekkuli'), ('keksijä'), ('keljuus'), ('kellari'), ('kellata'), ('kelluke'), ('kellute'),
('kelmetä'), ('kelmeys'), ('kelokko'), ('kelopuu'), ('keltamo'), ('keltano'), ('kelvata'), ('kemisti'), ('kenguru'), ('kenkäin'),
('kenkään'), ('kenopää'), ('kenossa'), ('kenties'), ('kepakko'), ('kepitys'), ('keppana'), ('keppari'), ('keraami'), ('keralla'),
('keralle'), ('kerintä'), ('kerjetä'), ('kerjätä'), ('kerjäys'), ('kerkeys'), ('kerrata'), ('kerroin'), ('kerskua'), ('kertaus'),
('kertoin'), ('kertoja'), ('kertoma'), ('kertymä'), ('keräily'), ('keräymä'), ('kerääjä'), ('kesakko'), ('kesanto'), ('keskari'),
('keskeen'), ('keskiyö'), ('kestitä'), ('kestävä'), ('kesysti'), ('kesytys'), ('kesytön'), ('kesäkuu'), ('kesäpuu'), ('kesäsää'),
('kesätyö'), ('ketchup'), ('ketkale'), ('ketlata'), ('ketoosi'), ('ketterä'), ('kicksit'), ('kidutus'), ('kiehtoa'), ('kiehätä'),
('kiekaus'), ('kiekuja'), ('kiekuna'), ('kiekura'), ('kielari'), ('kieleke'), ('kielevä'), ('kielijä'), ('kieltää'), ('kiemura'),
('kiepaus'), ('kieppua'), ('kierous'), ('kierrin'), ('kierros'), ('kiertue'), ('kiertyä'), ('kiertää'), ('kieryys'), ('kieunta'),
('kievari'), ('kihdata'), ('kihistä'), ('kihlata'), ('kihlaus'), ('kihokki'), ('kihveli'), ('kiihkeä'), ('kiihoke'), ('kiihote'),
('kiihtyä'), ('kiikari'), ('kiikkua'), ('kiilata'), ('kiilaus'), ('kiiltää'), ('kiinata'), ('kiinteä'), ('kiintiö'), ('kiintyä'),
('kiipeli'), ('kiipijä'), ('kiireys'), ('kiiruna'), ('kiistää'), ('kiittää'), ('kiitäjä'), ('kiivaus'), ('kiivetä'), ('kikatus'),
('kikkara'), ('kikkare'), ('kikkeli'), ('kikpapu'), ('kilistä'), ('kiljaus'), ('kiljuva'), ('kilkkaa'), ('killeri'), ('killiin'),
('kimaira'), ('kimakka'), ('kimalle'), ('kimeeri'), ('kimitys'), ('kimmoke'), ('kimmota'), ('kimpale'), ('kimpsut'), ('kinailu'),
('kiniini'), ('kinkata'), ('kintere'), ('kinuski'), ('kipaisu'), ('kipakka'), ('kippari'), ('kippura'), ('kipsata'), ('kipsaus'),
('kirahvi'), ('kirjain'), ('kirjake'), ('kirjata'), ('kirjaus'), ('kirjava'), ('kirjuri'), ('kirkuna'), ('kirkuva'), ('kirmata'),
('kirnuta'), ('kiroilu'), ('kirottu'), ('kirpeys'), ('kirppis'), ('kirskua'), ('kirurgi'), ('kirveli'), ('kirvely'), ('kirvota'),
('kisailu'), ('kiskoja'), ('kiskuri'), ('kisälli'), ('kiteymä'), ('kitiini'), ('kitistä'), ('kitkerä'), ('kitkerö'), ('kitsaus'),
('kittana'), ('kittaus'), ('kitumaa'), ('kitupuu'), ('kituset'), ('kiusata'), ('kiusaus'), ('kivasti'), ('kiveliö'), ('kivetys'),
('kivikko'), ('kivinen'), ('kivirae'), ('kivitys'), ('kivityö'), ('kivuton'), ('kivääri'), ('klarkia'), ('klezmer'), ('kliivia'),
('klikata'), ('klimppi'), ('klingon'), ('klintti'), ('klootti'), ('kluutti'), ('klöntti'), ('knaappi'), ('knesset'), ('kodikas'),
('koditon'), ('koeaika'), ('koeajaa'), ('koepala'), ('koestaa'), ('koestus'), ('koettaa'), ('kohdata'), ('kohista'), ('kohkata'),
('kohmelo'), ('kohoama'), ('kohokas'), ('kohokki'), ('koholla'), ('koholle'), ('kohosuo'), ('kohotus'), ('kohouma'), ('kohtaan'),
('kohtalo'), ('kohtaus'), ('kohtelu'), ('kohtuus'), ('koiruus'), ('koisata'), ('koittaa'), ('kokardi'), ('kokeilu'), ('kokelas'),
('kokemus'), ('kokenut'), ('koketti'), ('kokkare'), ('kokkaus'), ('kokkeli'), ('kokoaja'), ('kokooja'), ('kokotti'), ('kokouma'),
('koksata'), ('kolapuu'), ('kolehti'), ('kolibri'), ('kolikko'), ('kolista'), ('kolkata'), ('kolkkaa'), ('kollata'), ('kollega'),
('kolonia'), ('kolonna'), ('kolonni'), ('kolopuu'), ('kolossi'), ('kolotus'), ('kolumni'), ('komedia'), ('komeilu'), ('komento'),
('komitea'), ('kommari'), ('kompata'), ('kompura'), ('komuuti'), ('kondomi'), ('kondori'), ('konetyö'), ('konkari'), ('konkata'),
('konkelo'), ('konnari'), ('konnuus'), ('konsaan'), ('konsoli'), ('konsuli'), ('kontata'), ('koodari'), ('koodata'), ('koodaus'),
('koolata'), ('koolaus'), ('koommin'), ('koonnos'), ('koontaa'), ('koostaa'), ('koostua'), ('kopista'), ('kopisti'), ('koplata'),
('koplaus'), ('koppari'), ('koppava'), ('koppelo'), ('koppero'), ('koppura'), ('kopsata'), ('kopsaus'), ('kopteri'), ('kopukka'),
('koputus'), ('koraali'), ('Koraani'), ('koralli'), ('koreilu'), ('korento'), ('korista'), ('koriste'), ('korityö'), ('korjain'),
('korjata'), ('korjaus'), ('korjuri'), ('korjuun'), ('korkata'), ('korkeus'), ('korkita'), ('koroste'), ('koroton'), ('korotus'),
('korskea'), ('korskua'), ('korundi'), ('koruton'), ('korvake'), ('korvata'), ('korvaus'), ('korveta'), ('korvike'), ('kosinta'),
('koskaan'), ('koskelo'), ('kosolti'), ('kostaja'), ('kosteus'), ('kostuke'), ('kostute'), ('kotiapu'), ('kotiasu'), ('kotijää'),
('kotimaa'), ('kotiovi'), ('kotitie'), ('kotityö'), ('kotkata'), ('kotkaus'), ('kotoilu'), ('kotoisa'), ('kotomaa'), ('kottero'),
('koturni'), ('koukata'), ('koukero'), ('koukuta'), ('koulata'), ('kovalla'), ('kovalle'), ('kovasin'), ('kovassa'), ('kovasti'),
('koverre'), ('kovetus'), ('kovilla'), ('koville'), ('kovitus'), ('krakata'), ('kramppi'), ('kranssi'), ('kranttu'), ('krapula'),
('kreikka'), ('kremppa'), ('krepata'), ('kroatia'), ('kroisos'), ('kromata'), ('kromaus'), ('krookus'), ('kruksia'), ('krypton'),
('kränätä'), ('kubismi'), ('kubisti'), ('kudelma'), ('kudonta'), ('kuhilas'), ('kuhista'), ('kuhmura'), ('kuhnuri'), ('kuhunka'),
('kuihtua'), ('kuikelo'), ('kuirimo'), ('kuiskia'), ('kuitata'), ('kuivain'), ('kuivata'), ('kuivate'), ('kuivaus'), ('kuiviin'),
('kuivike'), ('kuivuri'), ('kuivuus'), ('kujanne'), ('kujeilu'), ('kukikas'), ('kukinta'), ('kukinto'), ('kukitus'), ('kukkaro'),
('kukkeus'), ('kukkula'), ('kukkura'), ('kukunta'), ('kulakki'), ('kulissi'), ('kulitsa'), ('kulkija'), ('kulkuri'), ('kullata'),
('kullero'), ('kulmata'), ('kulmaus'), ('kultala'), ('kultaus'), ('kuluerä'), ('kulunki'), ('kulussa'), ('kulutus'), ('kulööri'),
('kumajaa'), ('kuminen'), ('kumipuu'), ('kumissi'), ('kumista'), ('kummata'), ('kummeli'), ('kummeta'), ('kummius'), ('kummuta'),
('kumossa'), ('kumotus'), ('kumpare'), ('kumpeli'), ('kunnari'), ('kuntoon'), ('kuohari'), ('kuohita'), ('kuohkea'), ('kuohuta'),
('kuohuva'), ('kuokkia'), ('kuolata'), ('kuolema'), ('kuollut'), ('kuontua'), ('kuopake'), ('kuopata'), ('kuorike'), ('kuorimo'),
('kuortua'), ('kupliva'), ('kuponki'), ('kuppari'), ('kuppaus'), ('kuppila'), ('kuriiri'), ('kurikka'), ('kurimus'), ('kurista'),
('kuriton'), ('kuritus'), ('kurjuus'), ('kurkata'), ('kurkkia'), ('kurkuma'), ('kurlata'), ('kurlaus'), ('kurouma'), ('kursori'),
('kurvata'), ('kusetus'), ('kusinen'), ('kusipää'), ('kuskata'), ('kuskaus'), ('kutista'), ('kutitus'), ('kutkuta'), ('kutonen'),
('kutsuja'), ('kutteri'), ('kuttula'), ('kutyymi'), ('kuualus'), ('kuuauto'), ('kuukivi'), ('kuulaus'), ('kuulema'), ('kuulija'),
('kuuloke'), ('kuultaa'), ('kuuluva'), ('kuumeta'), ('kuumuus'), ('kuunaan'), ('kuunari'), ('kuuperä'), ('kuurata'), ('kuuraus'),
('kuurous'), ('kuusama'), ('kuusilo'), ('kuutamo'), ('kuvaaja'), ('kuvaamo'), ('kuvaava'), ('kuvailu'), ('kuvasto'), ('kuvatus'),
('kuvitus'), ('kuvotus'), ('kvantti'), ('kvarkki'), ('kvartsi'), ('kvartti'), ('kvintti'), ('kyborgi'), ('kydötys'), ('kyhäily'),
('kyllyys'), ('kylmetä'), ('kylmyys'), ('kylmätä'), ('kylpijä'), ('kylpylä'), ('kylteri'), ('kylväjä'), ('kyläily'), ('kylässä'),
('kylästä'), ('kylätie'), ('kynsimö'), ('kynteli'), ('kynttää'), ('kyntäjä'), ('kynäily'), ('kypsetä'), ('kypsyys'), ('kyrmyyn'),
('kyräily'), ('kysellä'), ('kyssäri'), ('kysymys'), ('kysyntä'), ('kyttyrä'), ('kyttäys'), ('kyvykäs'), ('kyvytön'), ('kyyditä'),
('kyykkiä'), ('kyykätä'), ('kyylätä'), ('kyynele'), ('kyynärä'), ('kyyryyn'), ('kyöpeli'), ('kyörätä'), ('kädetön'), ('kähistä'),
('käkkyrä'), ('käkkärä'), ('käkätin'), ('käkätys'), ('käkönen'), ('kälppiä'), ('kälynen'), ('kämmätä'), ('kämmäys'), ('kämppis'),
('kämänen'), ('känistä'), ('kännätä'), ('kännäys'), ('käppyrä'), ('käppänä'), ('kärhämä'), ('käriste'), ('käristä'), ('kärkevä'),
('kärkkyä'), ('kärräri'), ('kärrätä'), ('kärräys'), ('kärsijä'), ('kärsämö'), ('kärttää'), ('kärytys'), ('käräjät'), ('käsiala'),
('käsiase'), ('käsiksi'), ('käsille'), ('käsillä'), ('käsiote'), ('käsipuu'), ('käsissä'), ('käsitys'), ('käsityö'), ('käskijä'),
('kässäri'), ('kässätä'), ('kätellä'), ('kätkijä'), ('kättely'), ('kätönen'), ('kävellä'), ('käväisy'), ('käymälä'), ('käypyys'),
('käyryys'), ('käyttää'), ('käytävä'), ('käyvyys'), ('käännin'), ('käännös'), ('kääntyä'), ('kääntää'), ('kääryle'), ('köhistä'),
('kömpelö'), ('köriläs'), ('köyhetä'), ('köyhtyä'), ('köyhyys'), ('köynnös'), ('köyryyn'), ('köyttää');

-- Words starting with L
INSERT INTO finnish_words(word) VALUES
('laahata'), ('laahaus'), ('laajeta'), ('laajuus'), ('laakeri'), ('laantua'), ('laatija'), ('labiili'), ('ladella'), ('ladelma'),
('ladonta'), ('ladusto'), ('laguuni'), ('lahdata'), ('lahdeke'), ('lahjoma'), ('lahokas'), ('lahokka'), ('lahopuu'), ('lahouma'),
('lahtari'), ('laiheta'), ('laihtua'), ('laihuus'), ('laimeta'), ('laimeus'), ('lainata'), ('lainaus'), ('laistaa'), ('laitama'),
('laittaa'), ('laituri'), ('laivata'), ('laivaus'), ('laivuri'), ('lajikas'), ('lajisto'), ('lajitin'), ('lakaisu'), ('lakeeri'),
('lakeija'), ('lakiosa'), ('lakkaus'), ('lamassa'), ('lamasta'), ('lambada'), ('lamelli'), ('lamoava'), ('lampare'), ('lampola'),
('lampsia'), ('lampuri'), ('langata'), ('langeta'), ('lankata'), ('lankaus'), ('lankous'), ('lantala'), ('lantata'), ('laottaa'),
('lapakko'), ('lapaluu'), ('lapanen'), ('lapikas'), ('lapseus'), ('lapsuus'), ('larpata'), ('lasagne'), ('lasikko'), ('lasinen'),
('lasiovi'), ('lasisto'), ('lasitus'), ('lasityö'), ('laskija'), ('laskimo'), ('laskuri'), ('lassota'), ('lastain'), ('lastata'),
('lastaus'), ('lastuta'), ('lataamo'), ('latauma'), ('lateksi'), ('latinki'), ('latomus'), ('lattana'), ('lattari'), ('latteus'),
('latuska'), ('lauheta'), ('lauhkea'), ('lauhtua'), ('laukata'), ('laukaus'), ('laukkoa'), ('laulaja'), ('laulava'), ('laupeus'),
('laupias'), ('lauseke'), ('lausuja'), ('lausuma'), ('lautata'), ('lauteet'), ('lautuma'), ('lavaste'), ('lavetti'), ('laviini'),
('lavitsa'), ('leasing'), ('legenda'), ('leghorn'), ('lehteri'), ('lehtevä'), ('lehtori'), ('leijata'), ('leijona'), ('leijuma'),
('leikari'), ('leikata'), ('leikkiä'), ('leikkuu'), ('leimata'), ('leimaus'), ('leimuta'), ('leipoja'), ('leipomo'), ('leipuri'),
('leiskua'), ('leivite'), ('lekkeri'), ('lempata'), ('lempeys'), ('leninki'), ('lenkata'), ('lenkous'), ('lentely'), ('lentäjä'),
('lentävä'), ('lepakko'), ('lepatus'), ('lepikko'), ('lepikkö'), ('lepistö'), ('leppeys'), ('lepsuus'), ('leptoni'), ('lepytys'),
('lerppua'), ('lesbous'), ('leskeys'), ('lespata'), ('lespaus'), ('letaali'), ('letkaus'), ('letkeys'), ('letukka'), ('leudota'),
('leuhkia'), ('leukava'), ('leutous'), ('leveily'), ('levikki'), ('levintä'), ('levitin'), ('levitys'), ('leviäin'), ('levoton'),
('levystö'), ('levytys'), ('leväkkö'), ('liehtoa'), ('liehuke'), ('lientyä'), ('lientää'), ('liereys'), ('liestyä'), ('liesuta'),
('lietsoa'), ('liettua'), ('liettyä'), ('liettää'), ('lievetä'), ('lievike'), ('lievyys'), ('liftari'), ('liftata'), ('liftaus'),
('lihaisa'), ('lihakas'), ('lihaton'), ('lihotus'), ('liiaksi'), ('liialti'), ('liiduta'), ('liikata'), ('liikkis'), ('liikkua'),
('liimata'), ('liimaus'), ('liipata'), ('liirata'), ('liirtää'), ('liisata'), ('liisaus'), ('liitely'), ('liiteri'), ('liittyä'),
('liittää'), ('liivate'), ('likaaja'), ('likelle'), ('likellä'), ('likeltä'), ('likempi'), ('likinnä'), ('likvidi'), ('likvori'),
('likööri'), ('limakko'), ('limaska'), ('limetti'), ('limitin'), ('limitys'), ('lingota'), ('linjata'), ('linjaus'), ('linjuri'),
('linkata'), ('linkous'), ('linnake'), ('liottaa'), ('lipaisu'), ('lipasto'), ('liperit'), ('lipitys'), ('lipoidi'), ('lipokas'),
('lipsaus'), ('liputus'), ('liristä'), ('liritys'), ('lirutus'), ('listake'), ('listata'), ('listaus'), ('lisäetu'), ('lisäksi'),
('lisätyö'), ('litania'), ('litistä'), ('litsari'), ('littana'), ('littera'), ('litteys'), ('litukka'), ('liturgi'), ('liukuma'),
('liukuri'), ('liuotin'), ('liuotus'), ('lobbari'), ('lobbaus'), ('lobelia'), ('lohduke'), ('lohjeta'), ('lohkare'), ('loihtia'),
('loikata'), ('loikkia'), ('loimuta'), ('loiskia'), ('loiskua'), ('loistaa'), ('loitota'), ('loitsia'), ('loiveta'), ('loivuus'),
('lojaali'), ('lokakuu'), ('lokoisa'), ('lomailu'), ('lomassa'), ('lomasta'), ('lomitse'), ('lomitus'), ('lonkero'), ('lonksua'),
('loparit'), ('lopetus'), ('loppuun'), ('loppuyö'), ('lopuksi'), ('lopulla'), ('lopulta'), ('lopussa'), ('loputon'), ('lorista'),
('lossata'), ('lotista'), ('lotrata'), ('louferi'), ('louhimo'), ('loukata'), ('louskua'), ('lovinen'), ('lovitus'), ('lueksia'),
('luettaa'), ('luikata'), ('luikero'), ('luikkia'), ('luikuri'), ('luimuun'), ('luiseva'), ('luistaa'), ('luistin'), ('lujalla'),
('lujalle'), ('lujassa'), ('lujasta'), ('lujasti'), ('lujilla'), ('lujille'), ('lukaali'), ('lukitus'), ('lukkari'), ('lukkoon'),
('lukossa'), ('lukosta'), ('lukuisa'), ('lukupää'), ('lukuset'), ('lumetus'), ('lumierä'), ('lumikko'), ('luminen'), ('lumirae'),
('lumityö'), ('lumoava'), ('lumooja'), ('lunnaat'), ('luntata'), ('luodata'), ('luonnos'), ('luontua'), ('luopuja'), ('luotain'),
('luotaus'), ('luottaa'), ('luovuus'), ('lupaava'), ('lupailu'), ('lupiini'), ('luritus'), ('luserni'), ('lusikka'), ('lutikka'),
('lutukka'), ('lutunen'), ('luuhata'), ('luukala'), ('luukato'), ('luumätä'), ('luurata'), ('luuseri'), ('luusolu'), ('luusälö'),
('luutuma'), ('luututa'), ('luuvalo'), ('luuydin'), ('luvaton'), ('luvitus'), ('luvuton'), ('lyhenne'), ('lyhyeen'), ('lyijyke'),
('lyijytä'), ('lykkäys'), ('lyllerö'), ('lynkata'), ('lypsäjä'), ('lysteri'), ('lystätä'), ('lysyssä'), ('lyttyyn'), ('lytyssä'),
('lyöttyä'), ('lyöttää'), ('lähelle'), ('lähellä'), ('läheltä'), ('lähemmä'), ('lähempi'), ('lähetin'), ('lähetti'), ('lähetys'),
('lähinnä'), ('lähistö'), ('lähityö'), ('lähtien'), ('lähtijä'), ('läikkyä'), ('läimätä'), ('läimäys'), ('läiskiä'), ('läiskyä'),
('läjitys'), ('lälläri'), ('lämmetä'), ('lämmike'), ('lämmitä'), ('lämpäre'), ('läntätä'), ('läpiajo'), ('läppäri'), ('läpsäys'),
('läpyskä'), ('läpytys'), ('läpäisy'), ('läpätys'), ('lätistä'), ('läträtä'), ('lättänä'), ('lätäkkö'), ('lävikkö'), ('läviste'),
('lävitse'), ('lääkitä'), ('lääkäri'), ('lääppiä'), ('löhöily'), ('löpistä'), ('löyhetä'), ('löyhtyä'), ('löyhyys'), ('löystyä'),
('löysyys'), ('löysätä'), ('löytäjä'), ('lööperi');

-- Words starting with M
INSERT INTO finnish_words(word) VALUES
('maailma'), ('maakari'), ('maakuva'), ('maalaji'), ('maalari'), ('maalata'), ('maalaus'), ('maamies'), ('maamuna'), ('maanisä'),
('maannos'), ('maanosa'), ('maantaa'), ('maantie'), ('maaorja'), ('maapala'), ('maapato'), ('maaperä'), ('maapeto'), ('maaraja'),
('maarata'), ('maasota'), ('maatalo'), ('maatila'), ('maattaa'), ('maatuma'), ('maavara'), ('maavesi'), ('maaväri'), ('maaäiti'),
('maaöljy'), ('macaron'), ('madeira'), ('madella'), ('madonna'), ('madotus'), ('maestro'), ('mafioso'), ('magenta'), ('mahakas'),
('mahatma'), ('mahjong'), ('mahonia'), ('mahonki'), ('mahtaja'), ('mahtava'), ('maidoke'), ('maihari'), ('mailata'), ('mailaus'),
('maileri'), ('mainari'), ('mainita'), ('maireus'), ('maisema'), ('maistaa'), ('maistua'), ('maittaa'), ('majailu'), ('majakka'),
('makeilu'), ('makeute'), ('makkara'), ('makkari'), ('makoilu'), ('makoisa'), ('makroni'), ('maksaja'), ('maksimi'), ('malaiji'),
('malaria'), ('maligni'), ('malikka'), ('mallata'), ('malline'), ('maltaat'), ('malttaa'), ('mammona'), ('manaaja'), ('manailu'),
('mandala'), ('maneeri'), ('maneesi'), ('manilla'), ('maniska'), ('mankeli'), ('mankuja'), ('manteli'), ('mantere'), ('maoismi'),
('mapitus'), ('marakas'), ('maraton'), ('marenki'), ('marimba'), ('marista'), ('marmori'), ('marsala'), ('marssia'), ('martini'),
('martous'), ('masiina'), ('maskara'), ('masmalo'), ('massata'), ('massaus'), ('masuuni'), ('materia'), ('matikka'), ('matinea'),
('matkata'), ('matkija'), ('matonen'), ('maukuna'), ('maustaa'), ('maustua'), ('meduusa'), ('mehuisa'), ('mehujää'), ('mehukas'),
('mehuste'), ('meijeri'), ('meikata'), ('meilata'), ('meilaus'), ('meinata'), ('meioosi'), ('meirami'), ('meistää'), ('mekkala'),
('meklari'), ('melassi'), ('melkein'), ('melodia'), ('melonta'), ('meluaja'), ('meluisa'), ('menarke'), ('menekki'), ('menetys'),
('menoerä'), ('mentoli'), ('mentori'), ('merijää'), ('merisää'), ('meritie'), ('meritse'), ('merkata'), ('merkeli'), ('merkitä'),
('mesikkä'), ('messevä'), ('messias'), ('messiin'), ('messuta'), ('mestari'), ('mestata'), ('mestaus'), ('metaani'), ('metakka'),
('metalli'), ('meteori'), ('metinen'), ('metsuri'), ('metsälö'), ('miehevä'), ('mieheys'), ('miehuus'), ('miehyys'), ('mieleen'),
('mielevä'), ('mieltyä'), ('mieltää'), ('miestyö'), ('mietous'), ('miettiä'), ('mihinkä'), ('miinata'), ('mikkeli'), ('mikrobi'),
('mikroni'), ('miksata'), ('miksaus'), ('mikseri'), ('mikäkin'), ('miliisi'), ('milloin'), ('millään'), ('mimesis'), ('mimoosa'),
('minnekä'), ('mirhami'), ('mispeli'), ('missata'), ('misseys'), ('missiys'), ('missään'), ('misteli'), ('mistään'), ('misääri'),
('mitalli'), ('mitella'), ('mitellä'), ('mitenkä'), ('mitoosi'), ('mitsuba'), ('mittain'), ('mittari'), ('mittaus'), ('mittava'),
('mittely'), ('mittelö'), ('mitätön'), ('mobbaus'), ('mobiili'), ('modaali'), ('modeemi'), ('moderni'), ('modisti'), ('moduuli'),
('moikata'), ('moikina'), ('moittia'), ('moksaus'), ('mollata'), ('mollaus'), ('molotus'), ('molskia'), ('monasti'), ('monesti'),
('mongoli'), ('moniajo'), ('monikko'), ('monismi'), ('moniste'), ('monisti'), ('moppaus'), ('moraali'), ('moreeni'), ('morjens'),
('morkata'), ('morkkis'), ('mormoni'), ('morsian'), ('moshata'), ('moshaus'), ('motelli'), ('motetti'), ('motiivi'), ('moukari'),
('mouruta'), ('muffini'), ('mufloni'), ('muhkeus'), ('muhkura'), ('muinoin'), ('muistaa'), ('muistio'), ('muistua'), ('mukailu'),
('mukamas'), ('mukauma'), ('mukista'), ('muksaus'), ('mulatti'), ('muljaus'), ('mulkero'), ('mullata'), ('multain'), ('multaus'),
('multava'), ('mumista'), ('mummeli'), ('mummola'), ('munakas'), ('munaton'), ('munavoi'), ('muninta'), ('munitus'), ('muodota'),
('muokata'), ('muovata'), ('muovaus'), ('muraali'), ('muratti'), ('mureena'), ('murhata'), ('murikka'), ('murista'), ('murkina'),
('murmeli'), ('murtaja'), ('murtuma'), ('murunen'), ('musakas'), ('musikka'), ('muskari'), ('muskeli'), ('muslimi'), ('mustata'),
('musteta'), ('mustuma'), ('mustuus'), ('mutista'), ('mutruun'), ('mutteri'), ('muualla'), ('muualle'), ('muualta'), ('muuanne'),
('muunnin'), ('muunnos'), ('muuntaa'), ('muuntua'), ('muurain'), ('muurari'), ('muurata'), ('muuraus'), ('muusata'), ('muutama'),
('muutoin'), ('muuttaa'), ('muuttua'), ('myalgia'), ('myhkyrä'), ('myhäily'), ('mykkyrä'), ('mykkyys'), ('mylläri'), ('myllätä'),
('mylvinä'), ('mynkään'), ('myriadi'), ('myräkkä'), ('myymälä'), ('myödätä'), ('myöhään'), ('myöntyä'), ('myöntää'), ('myöskin'),
('myöstää'), ('myötäle'), ('mädätys'), ('mäiskiä'), ('mäiskyä'), ('mäiskää'), ('mäkimaa'), ('mäkinen'), ('mäkätys'), ('mällätä'),
('märkile'), ('märkyys'), ('mäskänä'), ('mäskätä'), ('mäskäys'), ('mässätä'), ('mässäys'), ('mäsäksi'), ('mätkätä'), ('mätkäys'),
('mätsätä'), ('mätäkuu'), ('mäystin'), ('määintä'), ('määkinä'), ('määrite'), ('määrätä'), ('määräys'), ('möhkäle'), ('möhlätä'),
('möhläys'), ('mökötys'), ('mölistä'), ('mölötys'), ('mönjätä'), ('mönkijä'), ('mönkään'), ('möristä'), ('möräkkä'), ('mötikkä'),
('möyhätä'), ('möykätä'), ('möyrinä'), ('möyrytä'), ('mööpeli');

-- Words starting with N
INSERT INTO finnish_words(word) VALUES
('naamari'), ('naapuri'), ('naarata'), ('naaraus'), ('nahikas'), ('nahista'), ('nahkuri'), ('naiseus'), ('naisuus'), ('naittaa'), 
('nakella'), ('nakkelu'), ('naksaus'), ('nakuilu'), ('nakutus'), ('namikka'), ('namiska'), ('namunen'), ('napajää'), ('napakka'), 
('napista'), ('napitus'), ('nappeli'), ('nappula'), ('napsaus'), ('napukka'), ('naputus'), ('narikka'), ('narista'), ('narkata'), 
('narkkis'), ('narrata'), ('narraus'), ('narrius'), ('narskua'), ('narutus'), ('nasakka'), ('naskali'), ('nastata'), ('nastaus'), 
('natiivi'), ('natista'), ('natrium'), ('natsata'), ('nauhuri'), ('naukata'), ('naulain'), ('naulata'), ('naulaus'), ('naulita'), 
('nauraja'), ('nauttia'), ('navakka'), ('navetta'), ('neitsyt'), ('nektari'), ('nelikko'), ('nelikkö'), ('nelisen'), ('nelisin'), 
('nelisäe'), ('nelonen'), ('nenetsi'), ('nenäkäs'), ('nenäluu'), ('nenätti'), ('neppari'), ('neppaus'), ('nerokas'), ('nestori'), 
('neulata'), ('neuloja'), ('neuluri'), ('neuroni'), ('neuvoja'), ('neuvola'), ('new age'), ('nidonta'), ('nielaus'), ('niemeke'),
('nihkeys'), ('niistää'), ('niitata'), ('niittää'), ('nikkari'), ('nikkeli'), ('niklata'), ('nikotus'), ('niksaus'), ('nilelle'), 
('nilellä'), ('nimekäs'), ('nimetön'), ('nimikko'), ('niminen'), ('nimiosa'), ('nimistö'), ('nimitys'), ('nimmari'), ('niobium'), 
('nipotus'), ('nippeli'), ('nipsaus'), ('nipukka'), ('niputus'), ('nirhama'), ('nirhata'), ('nirskua'), ('nirvana'), ('niskuri'), 
('nispero'), ('nisäkäs'), ('nitistä'), ('niuketa'), ('nivaska'), ('nivunen'), ('noduuli'), ('noituus'), ('nojalla'), ('nojassa'), 
('nokinen'), ('nokitus'), ('nokkava'), ('nokkela'), ('nokoset'), ('nollata'), ('nollaus'), ('nolosti'), ('nonstop'), ('nopsaan'), 
('norjeta'), ('nostaja'), ('nostelu'), ('nosturi'), ('notaari'), ('notkeus'), ('noukkia'), ('nousija'), ('noutaja'), ('novelli'), 
('noviisi'), ('nudismi'), ('nudisti'), ('nugetti'), ('nuhjata'), ('nuhrata'), ('nuhtelu'), ('nuivuus'), ('nujakka'), ('nukitus'), 
('nukkaus'), ('nukkuja'), ('nukutus'), ('nulikka'), ('numerus'), ('nuntius'), ('nuohota'), ('nuohous'), ('nuokkua'), ('nuolija'), 
('nuoreta'), ('nuoriso'), ('nuortea'), ('nuortua'), ('nuoruus'), ('nuotata'), ('nupopää'), ('nupukki'), ('nurista'), ('nurkata'), 
('nutipää'), ('nuttura'), ('nutukas'), ('nuudeli'), ('nuuhkia'), ('nuukuus'), ('nuuskia'), ('nuutata'), ('nyanssi'), ('nyhjätä'), 
('nyhrätä'), ('nyhverö'), ('nykyasu'), ('nykytys'), ('nykyään'), ('nykäisy'), ('nylkyri'), ('nynnerö'), ('nyplätä'), ('nypläys'), 
('nyppylä'), ('nypykkä'), ('nyrpeys'), ('nystyrä'), ('nysverö'), ('nysvätä'), ('nytkäys'), ('nyyhkiä'), ('nyökkiä'), ('nyökätä'), 
('nähkääs'), ('nähtävä'), ('näkemys'), ('näkimet'), ('näkkäri'), ('näköala'), ('näplätä'), ('näppylä'), ('näppäin'), ('näppärä'),
('näppäys'), ('näprätä'), ('näpsäys'), ('näpäkkä'), ('närvänä'), ('nätisti'), ('näykkiä'), ('näykätä'), ('näyttää'), ('nääntyä'), 
('näätsen'), ('nöyrtyä'), ('nöyryys');

-- Words starting with O
INSERT INTO finnish_words(word) VALUES
('objekti'), ('oboisti'), ('odottaa'), ('oheinen'), ('ohennus'), ('ohentaa'), ('ohentua'), ('ohimeno'), ('ohittaa'), ('ohittua'),
('ohjaaja'), ('ohjaamo'), ('ohjailu'), ('ohjanta'), ('ohjelma'), ('ohuelti'), ('ohuesti'), ('ohuinen'), ('oikaisu'), ('oikeaan'),
('oikotie'), ('oikukas'), ('oireilu'), ('ojavalo'), ('ojennus'), ('ojentaa'), ('ojentua'), ('ojittaa'), ('okainen'), ('okasolu'),
('oksakas'), ('oksasto'), ('oksetus'), ('oksinta'), ('oksisto'), ('oktaani'), ('oktaavi'), ('oktetti'), ('oktetto'), ('oleilla'),
('oleksia'), ('olettaa'), ('oleutua'), ('olkaluu'), ('olkapää'), ('olkinen'), ('olkityö'), ('olkkari'), ('oloaika'), ('oloinen'),
('olosija'), ('olotila'), ('oltavat'), ('omainen'), ('omakehu'), ('omaksua'), ('omakuva'), ('omiansa'), ('omistaa'), ('omistus'),
('ommella'), ('ompelus'), ('ongelma'), ('onginta'), ('onnekas'), ('onneksi'), ('onnetar'), ('onneton'), ('onnikka'), ('ontosti'),
('onttous'), ('oopiumi'), ('ooppera'), ('ootrata'), ('ootraus'), ('opaakki'), ('opastaa'), ('opastin'), ('opastus'), ('opettaa'),
('opinala'), ('opinnot'), ('opintie'), ('opioidi'), ('oppilas'), ('oppinut'), ('optikko'), ('optinen'), ('opuntia'), ('oranssi'),
('orastaa'), ('orastua'), ('orastus'), ('oregano'), ('orgaani'), ('organdi'), ('orgasmi'), ('origami'), ('orjailu'), ('orkidea'),
('ortoosi'), ('orvakka'), ('orvokki'), ('osajako'), ('osittaa'), ('osmoosi'), ('osoitin'), ('osoitus'), ('ostella'), ('osuttaa'),
('osuvuus'), ('otaksua'), ('otattaa'), ('oteääni'), ('otsaluu'), ('otsikko'), ('oudokki'), ('oudosti'), ('ovaario'), ('oveluus'),
('ovensuu'), ('ovilevy'), ('ovimies'), ('ovivalo');

-- Words starting with P
INSERT INTO finnish_words(word) VALUES
('paahdin'), ('paahtaa'), ('paahtua'), ('paakari'), ('paalain'), ('paalata'), ('paalaus'), ('paapero'), ('paasata'), ('paavius'),
('pahanen'), ('pahasti'), ('pahiten'), ('pahkura'), ('paijata'), ('paijaus'), ('paikata'), ('paikkuu'), ('paikoin'), ('painaja'),
('painama'), ('painate'), ('painava'), ('painelu'), ('painija'), ('painike'), ('painuma'), ('paiskia'), ('paiskoa'), ('paistaa'),
('paistos'), ('paistua'), ('paisuma'), ('paitsio'), ('paituli'), ('pajatso'), ('pajatus'), ('pajukko'), ('pakaasi'), ('pakaste'),
('paketti'), ('pakista'), ('pakkari'), ('pakkaus'), ('pakkeli'), ('paklata'), ('paklaus'), ('pakoilu'), ('pakoora'), ('pakosti'),
('pakotie'), ('pakoton'), ('pakotus'), ('paksuta'), ('paksuus'), ('palanen'), ('palatsi'), ('palauma'), ('palaute'), ('palella'),
('paletti'), ('palikka'), ('paljous'), ('palkata'), ('palkita'), ('palkkio'), ('pallero'), ('pallura'), ('paloton'), ('palsami'),
('paltata'), ('palttaa'), ('palttoo'), ('palturi'), ('palvata'), ('palvaus'), ('palvelu'), ('palvoja'), ('pamista'), ('pampula'),
('paneeli'), ('paniini'), ('pannari'), ('pantata'), ('papaija'), ('papakoe'), ('papatti'), ('papatus'), ('papilla'), ('papilli'),
('papisto'), ('papitar'), ('paplari'), ('pappeus'), ('pappila'), ('paprika'), ('papyrus'), ('paraati'), ('parahin'), ('parakki'),
('paranee'), ('parempi'), ('parfait'), ('parhain'), ('parikki'), ('pariovi'), ('parisen'), ('parissa'), ('parista'), ('paristo'),
('pariton'), ('paritus'), ('parjata'), ('parjaus'), ('parkita'), ('parkkis'), ('parkour'), ('parkuna'), ('parodia'), ('parturi'),
('parveke'), ('pasaasi'), ('pasaati'), ('pasmata'), ('passari'), ('passata'), ('passeli'), ('pastori'), ('pasutus'), ('pasuuna'),
('pataani'), ('pateeni'), ('patetia'), ('patiini'), ('patonki'), ('patouma'), ('patteri'), ('patukka'), ('pauhata'), ('pauhina'),
('paukama'), ('paukata'), ('paukaus'), ('paukkaa'), ('paukkua'), ('pavlova'), ('pedaali'), ('peesata'), ('peeveli'), ('peeärrä'),
('pegasos'), ('pehmetä'), ('pehmeys'), ('pehmike'), ('pehmite'), ('pehmitä'), ('pehtori'), ('peilata'), ('peilaus'), ('peipata'),
('peitata'), ('peitota'), ('peittyä'), ('peittää'), ('pelaaja'), ('pelakuu'), ('peliasu'), ('peliote'), ('peliäly'), ('peljätä'),
('pelkuri'), ('pellava'), ('pelmeni'), ('pelmuta'), ('pelokas'), ('pelotin'), ('peloton'), ('pelotus'), ('pelätin'), ('pelätti'),
('penaali'), ('pendeli'), ('penikka'), ('penkata'), ('penkere'), ('penseys'), ('pentele'), ('peptidi'), ('peremmä'), ('perempi'),
('perenna'), ('pergola'), ('perhana'), ('periksi'), ('perilla'), ('perille'), ('perillä'), ('periltä'), ('perimys'), ('perinne'),
('perintä'), ('perintö'), ('periodi'), ('perkaus'), ('perkeet'), ('perkele'), ('perkule'), ('perperi'), ('perskat'), ('perukka'),
('perusta'), ('peruste'), ('peräevä'), ('perälle'), ('perällä'), ('perältä'), ('peräosa'), ('peräpää'), ('peräsin'), ('perässä'),
('perästä'), ('perätön'), ('pesintä'), ('pestata'), ('pestaus'), ('pesäero'), ('pesäpuu'), ('petkele'), ('petrata'), ('petraus'),
('petroli'), ('petsata'), ('petsaus'), ('petting'), ('petturi'), ('pettäjä'), ('petunia'), ('peuhata'), ('peukalo'), ('piccolo'),
('pidellä'), ('pidätin'), ('pidätys'), ('piekana'), ('pieksää'), ('pienetä'), ('piennar'), ('pienpuu'), ('pienuus'), ('piffata'),
('pihamaa'), ('pihapuu'), ('pihatie'), ('pihatto'), ('pihdata'), ('pihistä'), ('pihlaja'), ('pihtari'), ('piikata'), ('piikivi'),
('piilevä'), ('piiluta'), ('piinata'), ('piintyä'), ('piipata'), ('piirrin'), ('piirros'), ('piirtyä'), ('piirtää'), ('piisami'),
('piisata'), ('piisiru'), ('piisoni'), ('piitata'), ('pikeeri'), ('pikinen'), ('pikitie'), ('pikkolo'), ('pikkula'), ('pikseli'),
('pilaaja'), ('pilahvi'), ('pilailu'), ('pilalla'), ('pilalle'), ('pilates'), ('piletti'), ('pilkata'), ('pilkkiä'), ('pilkkoa'),
('pilleri'), ('pillike'), ('pilotti'), ('pilttuu'), ('pilvetä'), ('pimatsu'), ('pimento'), ('pimitys'), ('pimpata'), ('pineeni'),
('pinnari'), ('pinnata'), ('pinnaus'), ('pinseri'), ('pintaan'), ('pinteli'), ('pinttyä'), ('pipetti'), ('pippeli'), ('pippuri'),
('piraija'), ('piriste'), ('piristä'), ('pirpana'), ('pirskua'), ('pirstoa'), ('pirtelö'), ('pirteys'), ('piruilu'), ('pirusti'),
('pissata'), ('pistely'), ('pistoke'), ('pistävä'), ('pitaali'), ('pitaija'), ('pitkään'), ('pitämys'), ('piupaut'), ('plankki'),
('planssi'), ('planttu'), ('plarata'), ('plasebo'), ('platina'), ('playboy'), ('playoff'), ('pleissi'), ('plektra'), ('pluspuu'),
('pläjäys'), ('pläntti'), ('plörinä'), ('podcast'), ('podsoli'), ('poeetta'), ('pogromi'), ('pohatta'), ('pohjata'), ('pohjaus'),
('pohjola'), ('pohmelo'), ('poiketa'), ('poikuus'), ('poimija'), ('poimuri'), ('pointsi'), ('pointti'), ('poistaa'), ('poistin'),
('poistua'), ('pokaali'), ('pokkari'), ('polakka'), ('polanne'), ('polenta'), ('poletti'), ('poliisi'), ('pollari'), ('polotus'),
('polskia'), ('polttaa'), ('polveke'), ('pomoilu'), ('pompata'), ('pomppia'), ('pompula'), ('ponnari'), ('pontata'), ('ponteva'),
('popcorn'), ('poplari'), ('poplevy'), ('poplore'), ('poppana'), ('poppari'), ('poppeli'), ('poraaja'), ('poreilu'), ('poretin'),
('porista'), ('poroelo'), ('porotus'), ('porstua'), ('portaat'), ('portimo'), ('porukka'), ('porvari'), ('positio'), ('postata'),
('postaus'), ('postdoc'), ('posteri'), ('postite'), ('potaska'), ('potilas'), ('potkaus'), ('potkija'), ('potkuri'), ('potpuri'),
('poukama'), ('poukata'), ('poukota'), ('povaaja'), ('povekas'), ('poveton'), ('prakata'), ('praksis'), ('prameus'), ('preemio'),
('preeria'), ('preludi'), ('prepaid'), ('prepata'), ('presiis'), ('preussi'), ('priimas'), ('priimus'), ('prillit'), ('prinssi'),
('printti'), ('prologi'), ('promota'), ('pronssi'), ('propata'), ('protium'), ('protoni'), ('provota'), ('präntti'), ('pudokas'),
('pudotus'), ('puettaa'), ('puffata'), ('puhelin'), ('puhella'), ('puhista'), ('puhjeta'), ('puhkina'), ('puhtaus'), ('puhunta'),
('puhveli'), ('puijata'), ('puijaus'), ('puikelo'), ('puikkia'), ('puimala'), ('puimuri'), ('puiseva'), ('puistaa'), ('pujonta'),
('pujotus'), ('puketti'), ('pukimet'), ('pukkari'), ('pukkaus'), ('puklata'), ('pukuilu'), ('pulikka'), ('pulipää'), ('pulista'),
('puljata'), ('pullero'), ('pullote'), ('pulputa'), ('pulsari'), ('pultata'), ('pulteri'), ('pulveri'), ('pumaska'), ('pummata'),
('pummaus'), ('pumpata'), ('pumpuli'), ('pumputa'), ('punakka'), ('punakko'), ('punapuu'), ('punapää'), ('punerva'), ('punikki'),
('punkata'), ('punkero'), ('punktio'), ('punnita'), ('punonta'), ('puntari'), ('puntata'), ('puolain'), ('puolata'), ('puolaus'),
('puoleen'), ('puoliso'), ('puoliyö'), ('puoltaa'), ('pupilli'), ('puraisu'), ('purasin'), ('purenta'), ('purilas'), ('purismi'),
('puriste'), ('puristi'), ('purkaja'), ('purkamo'), ('purkaus'), ('purnari'), ('purnata'), ('purnaus'), ('purpura'), ('purpuri'),
('purseri'), ('purskua'), ('pursuta'), ('purtilo'), ('puruluu'), ('pusakka'), ('pusikko'), ('puskija'), ('puskuri'), ('pussata'),
('pusteli'), ('pustula'), ('putelli'), ('putinki'), ('putkilo'), ('putoaja'), ('putoama'), ('putsata'), ('putsaus'), ('puttaus'),
('puuaine'), ('puudeli'), ('puudute'), ('puuhake'), ('puuhata'), ('puujäte'), ('puukasa'), ('puukori'), ('puukuja'), ('puulaji'),
('puunata'), ('puunaus'), ('puupala'), ('puupino'), ('puuraja'), ('puurtaa'), ('puusolu'), ('puusäle'), ('puutalo'), ('puuteri'),
('puuttua'), ('puuvaja'), ('puuväri'), ('puvusto'), ('pyhimys'), ('pyhisin'), ('pyhitys'), ('pyhäkkö'), ('pyhästi'), ('pyhättö'),
('pyhätyö'), ('pylpyrä'), ('pyntätä'), ('pyrintä'), ('pyrintö'), ('pyrkijä'), ('pyrkyri'), ('pyrskiä'), ('pystyvä'), ('pystyyn'),
('pysäkki'), ('pytinki'), ('pyyhkiä'), ('pyykätä'), ('pyylevä'), ('pyytäjä'), ('pyällys'), ('pyältää'), ('pyöretä'), ('pyöreys'),
('pyörinä'), ('pyörtyä'), ('pyörtää'), ('pyörylä'), ('pyöräys'), ('pyöveli'), ('pähkinä'), ('pähkylä'), ('pähkämö'), ('päihtyä'),
('päitset'), ('päivyri'), ('päivätä'), ('päiväys'), ('pälyily'), ('pälätys'), ('pämpätä'), ('pänikkä'), ('pänkätä'), ('päntätä'),
('päristä'), ('pärjätä'), ('pärskiä'), ('pärskyä'), ('pärskää'), ('pätäkkä'), ('pääaine'), ('pääasia'), ('päähine'), ('pääisku'),
('pääjehu'), ('pääjoki'), ('pääkatu'), ('pääkipu'), ('päälaki'), ('päällys'), ('pääluku'), ('päämaja'), ('päämies'), ('päänoja'),
('pääntie'), ('pääpeli'), ('pääpiru'), ('päärata'), ('päärynä'), ('pääsana'), ('päästää'), ('pääteos'), ('päättyä'), ('päättää'),
('päätuki'), ('päätulo'), ('pääuoma'), ('pääväri'), ('pöhistä'), ('pöhötys'), ('pökkelö'), ('pökrätä'), ('pölistä'), ('pöllytä'),
('pölytys'), ('pölötys'), ('pömpeli'), ('pönikkä'), ('pönäkkä'), ('pönötys'), ('pöpistä'), ('pörhöön'), ('pöristä'), ('pörkölt'),
('pörrätä'), ('pörröön'), ('pötkylä'), ('pöydätä'), ('pöyheys'), ('pöyhkeä');

-- Words starting with Q
-- No words

-- Words starting with R
INSERT INTO finnish_words(word) VALUES
('raahata'), ('raahaus'), ('raakata'), ('raakile'), ('raakkua'), ('raakuus'), ('raapata'), ('raappia'), ('raaskia'), ('raastaa'),
('raastin'), ('raataja'), ('raatelu'), ('raatsia'), ('radisti'), ('raekoko'), ('raggari'), ('ragtime'), ('rahakas'), ('rahapuu'),
('rahasto'), ('rahaton'), ('rahdata'), ('rahista'), ('rahkeet'), ('rahtari'), ('rahtaus'), ('raihnas'), ('raijata'), ('raikuli'),
('railata'), ('rainata'), ('rainaus'), ('raiskio'), ('raisuus'), ('raivain'), ('raivari'), ('raivata'), ('raivaus'), ('raivota'),
('raivuri'), ('rajamaa'), ('rajaton'), ('rajoite'), ('rajusti'), ('rakenne'), ('raketti'), ('rakkaus'), ('rakkine'), ('rakkula'),
('rakoilu'), ('rakonen'), ('rakuuna'), ('ramadan'), ('rampata'), ('rampuus'), ('rankata'), ('ranketa'), ('ranking'), ('ranneke'),
('ranskis'), ('rantama'), ('raottaa'), ('raottua'), ('rapakko'), ('rapista'), ('raplata'), ('rappari'), ('rappaus'), ('rapsaus'),
('rapuvoi'), ('rasismi'), ('rasisti'), ('rasitus'), ('raskaus'), ('raspata'), ('rassata'), ('rassaus'), ('rasteri'), ('rasvata'),
('rasvaus'), ('rataosa'), ('ratatui'), ('ratikka'), ('ratista'), ('ratketa'), ('ratkoja'), ('ratsain'), ('ratsata'), ('rattaat'),
('raukeus'), ('raukkis'), ('rautias'), ('ravakka'), ('ravinne'), ('ravinto'), ('ravioli'), ('reaktio'), ('referee'), ('refilli'),
('reformi'), ('regatta'), ('regiimi'), ('rehtiys'), ('rehtori'), ('reikeli'), ('reilaan'), ('reilata'), ('reiluus'), ('reimari'),
('reitata'), ('reivata'), ('reivaus'), ('reiäkäs'), ('rejekti'), ('rekkari'), ('rekyyli'), ('reliefi'), ('relikti'), ('relissi'),
('remakka'), ('remissi'), ('rempata'), ('rempseä'), ('remuisa'), ('rentous'), ('repeämä'), ('replika'), ('reppana'), ('reppuri'),
('repuusi'), ('repäisy'), ('requiem'), ('resepti'), ('reservi'), ('resiina'), ('retiisi'), ('retikka'), ('retsina'), ('rettelö'),
('reuhake'), ('reuhata'), ('reuhtoa'), ('reunake'), ('reunama'), ('reviiri'), ('revintä'), ('revisio'), ('revitys'), ('revohka'),
('ricotta'), ('riekale'), ('riekkua'), ('rienata'), ('rienaus'), ('rientää'), ('rihkama'), ('rihlata'), ('rihlaus'), ('riippua'),
('riistää'), ('riitely'), ('riittyä'), ('riittää'), ('riivata'), ('rikaste'), ('rikkaus'), ('rikkoja'), ('rikkuri'), ('rimmata'),
('rimpula'), ('rinkeli'), ('rinkilä'), ('rinkula'), ('rintama'), ('rintava'), ('ripaska'), ('ripistä'), ('ripitys'), ('ripsari'),
('ripsaus'), ('risakas'), ('risiini'), ('riskilä'), ('risotto'), ('ristetä'), ('risteys'), ('ristiin'), ('risukko'), ('risutyö'),
('ritistä'), ('riuhtoa'), ('rivaali'), ('rivakka'), ('rivistö'), ('rivitys'), ('roaming'), ('robotti'), ('robusti'), ('rohista'),
('rohjake'), ('rohjeta'), ('rohkeus'), ('rohmuta'), ('rohtuma'), ('roihuta'), ('roikale'), ('roikkua'), ('roiskia'), ('roiskua'),
('rojalti'), ('rokkari'), ('rokokoo'), ('rokotus'), ('romaani'), ('romadur'), ('romania'), ('romista'), ('romutus'), ('ronkeli'),
('ronkkia'), ('rooteli'), ('ropista'), ('roponen'), ('ropsaus'), ('rosetti'), ('roskata'), ('rosolli'), ('rosteri'), ('rosvota'),
('rosvous'), ('rotinat'), ('rotisko'), ('rottelo'), ('roudari'), ('roudata'), ('rouille'), ('rouskua'), ('rovasti'), ('royalty'),
('rubiini'), ('ruikata'), ('ruikkia'), ('ruikuli'), ('ruinata'), ('ruipelo'), ('ruiskia'), ('rukkaus'), ('rukoilu'), ('ruksata'),
('ruletti'), ('rullata'), ('rullaus'), ('rumasti'), ('rumilus'), ('rumpali'), ('runkata'), ('runnata'), ('runoasu'), ('runoilu'),
('runosto'), ('runosäe'), ('runotar'), ('runoton'), ('runsaus'), ('runtata'), ('runtelu'), ('ruoikko'), ('ruoisto'), ('ruokala'),
('ruokkia'), ('ruokota'), ('ruopata'), ('ruoskia'), ('ruostua'), ('rupeama'), ('rupinen'), ('rusakko'), ('rusetti'), ('rusisti'),
('rusokas'), ('rusokki'), ('rusotus'), ('rustata'), ('rustaus'), ('ruteeni'), ('rutiini'), ('rutista'), ('rutjake'), ('rutosti'),
('ruttuun'), ('rutussa'), ('ruusuke'), ('ruutana'), ('ruuvata'), ('ryhelmä'), ('ryhmyri'), ('ryittää'), ('rykelmä'), ('rykäisy'),
('rymistä'), ('rynnäri'), ('rynnätä'), ('ryntäys'), ('ryntäät'), ('rypytys'), ('ryskinä'), ('ryskätä'), ('rytistä'), ('ryttyyn'),
('rytyssä'), ('rytäkkä'), ('ryypätä'), ('ryystää'), ('ryysätä'), ('ryöhätä'), ('ryökäle'), ('ryöpytä'), ('ryöpätä'), ('ryöstää'),
('ryöväri'), ('ryövätä'), ('ryöväys'), ('rähistä'), ('rähjätä'), ('rähäkkä'), ('rähätys'), ('räikeys'), ('räikinä'), ('räikynä'),
('räiskiä'), ('räiskyä'), ('räjähde'), ('räknätä'), ('räknäys'), ('räkytys'), ('räkätti'), ('räkätys'), ('rällätä'), ('rämesuo'),
('rämistä'), ('rämäkkä'), ('rämäpää'), ('ränstyä'), ('räpiskä'), ('räpiskö'), ('räplätä'), ('räppänä'), ('räppäri'), ('räpsäys'),
('räpytys'), ('rätinki'), ('rätistä'), ('rätkätä'), ('rätvänä'), ('räväkkä'), ('räyhätä'), ('räyskiä'), ('räystäs'), ('rääkkyä'),
('rääkynä'), ('rääkätä'), ('rääppiä'), ('rääpäle'), ('räätäli'), ('rääyntä'), ('röhistä'), ('röhkinä'), ('rökitys'), ('rökkiin'),
('römäkkä'), ('rönsytä'), ('röntgen'), ('rötiskä'), ('rötiskö'), ('rötkäle'), ('röttelö'), ('röyhelö'), ('röyhkeä'), ('röyhytä'),
('röykkiö');

-- Words starting with S
INSERT INTO finnish_words(word) VALUES
('saakeli'), ('saakuri'), ('saamari'), ('saareke'), ('saarros'), ('saartaa'), ('saastua'), ('saatana'), ('saatava'), ('saattaa'),
('saattue'), ('sabatti'), ('sabayon'), ('sabloni'), ('sadanta'), ('sadasti'), ('sadatus'), ('sadeasu'), ('sadella'), ('sadesää'),
('sadetin'), ('sadetus'), ('sadismi'), ('sadisti'), ('sadusto'), ('sadutus'), ('safiiri'), ('safkata'), ('saflori'), ('saframi'),
('sahaaja'), ('sahapuu'), ('sahrami'), ('saippua'), ('sairaus'), ('saituri'), ('saituus'), ('saivare'), ('sakaali'), ('sakasti'),
('saketti'), ('sakeute'), ('sakkaus'), ('sakkeli'), ('sakotus'), ('saksata'), ('saksaus'), ('sakuska'), ('salailu'), ('salaiva'),
('salakka'), ('salaoja'), ('salaovi'), ('salassa'), ('saletti'), ('salliva'), ('salmeke'), ('salomaa'), ('salonki'), ('salpaus'),
('salskea'), ('saluuna'), ('salvain'), ('salvata'), ('salvoin'), ('samaani'), ('samalla'), ('samanne'), ('samassa'), ('samaten'),
('sambata'), ('sametti'), ('sammota'), ('sammuke'), ('sammute'), ('samoilu'), ('samooja'), ('samoosa'), ('samotti'), ('samperi'),
('samurai'), ('sanailu'), ('sananen'), ('sanasto'), ('sanaton'), ('sanelin'), ('sanella'), ('sangria'), ('sankari'), ('sanketa'),
('sanktio'), ('sanomus'), ('sanonta'), ('sanottu'), ('saostaa'), ('saostin'), ('saostua'), ('saostus'), ('sapatti'), ('sapekas'),
('sapiska'), ('sapuska'), ('sarkain'), ('sarkaus'), ('sarveke'), ('sashimi'), ('sassiin'), ('satanen'), ('satiini'), ('satiiri'),
('satoisa'), ('satsata'), ('satsaus'), ('satsuma'), ('sattuma'), ('sattuva'), ('satuikä'), ('satuilu'), ('satumaa'), ('satyyri'),
('sauhuta'), ('saumain'), ('saumari'), ('saumata'), ('saumaus'), ('saumuri'), ('saunoja'), ('sauramo'), ('sauvoin'), ('savakko'),
('savanni'), ('savetus'), ('savikka'), ('savikko'), ('savimaa'), ('savinen'), ('savotta'), ('savuton'), ('savutus'), ('scherzo'),
('schäfer'), ('seerumi'), ('seesami'), ('seestyä'), ('seestää'), ('seilata'), ('seinäke'), ('seinämä'), ('seisake'), ('seisaus'),
('seisoja'), ('seisoma'), ('seisova'), ('sekaiho'), ('sekauma'), ('sekoilu'), ('sekoite'), ('sekopää'), ('sektori'), ('sekunda'),
('sekunti'), ('selailu'), ('seleeni'), ('selitys'), ('seljetä'), ('selkeys'), ('selkäin'), ('selleri'), ('seloste'), ('selusta'),
('selvetä'), ('selvitä'), ('selvyys'), ('selänne'), ('selätys'), ('selätön'), ('seniili'), ('seniori'), ('sensori'), ('senssit'),
('sentata'), ('sentään'), ('seostaa'), ('seostus'), ('sepalus'), ('sepitys'), ('seppele'), ('septimi'), ('seriffi'), ('serveri'),
('sesonki'), ('sesuura'), ('setteri'), ('seukata'), ('seurata'), ('seuraus'), ('sfinksi'), ('shakata'), ('shampoo'), ('sheavoi'),
('sheikki'), ('shiatsu'), ('shopata'), ('sidonta'), ('sidotus'), ('siemaus'), ('sienimö'), ('siepata'), ('sierain'), ('sievetä'),
('sievyys'), ('sifonki'), ('signumi'), ('sihdata'), ('sihistä'), ('sihtaus'), ('siideri'), ('siilata'), ('siintää'), ('siirrin'),
('siirros'), ('siirtyä'), ('siirtää'), ('siistiä'), ('siitake'), ('siittiö'), ('siittyä'), ('siittää'), ('siiveke'), ('siivilä'),
('siivota'), ('siivous'), ('sijaita'), ('sijaton'), ('sikailu'), ('sikermä'), ('sikiäin'), ('sikkara'), ('sikkura'), ('siklata'),
('sikseen'), ('silakka'), ('silitys'), ('silleen'), ('silloin'), ('sillään'), ('silmuri'), ('silmäke'), ('silmätä'), ('silmäys'),
('silosäe'), ('silotus'), ('silputa'), ('siltään'), ('siluuri'), ('sinappi'), ('sinelmä'), ('sinervä'), ('sinetti'), ('singota'),
('sininen'), ('sinkata'), ('sinkilä'), ('sinkitä'), ('sinuksi'), ('sinänsä'), ('sipaisu'), ('sipatti'), ('sipissä'), ('sipistä'),
('sippiin'), ('sireeni'), ('siristä'), ('siritys'), ('sirkoni'), ('sironta'), ('sirotin'), ('sirotus'), ('sirpale'), ('sirriin'),
('sirtaki'), ('sirunen'), ('sirutus'), ('sisarus'), ('sisemmä'), ('sisempi'), ('sisinnä'), ('siskous'), ('sisukas'), ('sisusta'),
('sisuste'), ('sisäkkö'), ('sisälle'), ('sisällä'), ('sisältä'), ('sisältö'), ('sisämaa'), ('sisäosa'), ('sisäovi'), ('sisässä'),
('sisästä'), ('sisätyö'), ('sitaisu'), ('sitkaan'), ('sitketä'), ('sitkeys'), ('sitteri'), ('siunata'), ('siunaus'), ('sivakka'),
('sivellä'), ('sivetti'), ('siviili'), ('sivuaja'), ('sivulla'), ('sivulle'), ('sivulta'), ('sivuosa'), ('sivuovi'), ('sivussa'),
('sivusta'), ('sivusto'), ('sivutie'), ('sivutyö'), ('sixpack'), ('skanssi'), ('skarppi'), ('skeitti'), ('skepsis'), ('skiitta'),
('skipata'), ('skonssi'), ('skriini'), ('skripta'), ('skruuvi'), ('skulata'), ('skumppa'), ('skunkki'), ('skuuppi'), ('skuutti'),
('slovari'), ('smetana'), ('sminkki'), ('smoking'), ('snooker'), ('sodomia'), ('sofista'), ('sofisti'), ('sohaisu'), ('sohlata'),
('soikeus'), ('soimata'), ('soimaus'), ('sointua'), ('soistaa'), ('soistua'), ('soisuus'), ('soittaa'), ('sojolla'), ('sojolle'),
('sojossa'), ('sokkeli'), ('sokkelo'), ('solakka'), ('solista'), ('solisti'), ('solkata'), ('solmita'), ('solmuke'), ('solukko'),
('solutus'), ('solutyö'), ('solvata'), ('solvaus'), ('somasti'), ('somiste'), ('sonetti'), ('soopeli'), ('sopeuma'), ('sopimus'),
('sopuilu'), ('sopuisa'), ('sopukka'), ('soratie'), ('sorista'), ('soritus'), ('sorjeta'), ('sorkkia'), ('sorsimo'), ('sortaja'),
('sortsit'), ('sortuma'), ('sorvari'), ('sorvata'), ('sorvaus'), ('sotaisa'), ('sotiisi'), ('sotilas'), ('sotkuun'), ('souketa'),
('soutaja'), ('soutelu'), ('sovelma'), ('sovinto'), ('sovitin'), ('sovitus'), ('spektri'), ('speltti'), ('spesies'), ('spesifi'),
('spiikki'), ('spondee'), ('sportti'), ('spurtti'), ('stadion'), ('stanssi'), ('startti'), ('stepata'), ('stilton'), ('stollen'),
('stondis'), ('stopata'), ('strassi'), ('stressi'), ('strippi'), ('strutsi'), ('struuma'), ('stuntti'), ('suahili'), ('suhista'),
('suhteen'), ('suihkia'), ('suikale'), ('suikata'), ('suikula'), ('suinkin'), ('suipeta'), ('suistaa'), ('suistua'), ('suitsea'),
('suitset'), ('suitsia'), ('sujakka'), ('sukanen'), ('sukitus'), ('sukkela'), ('sukkula'), ('sukupuu'), ('sulatto'), ('sulatus'),
('sulauma'), ('sulfidi'), ('sulitus'), ('sulkava'), ('sulkija'), ('suloisa'), ('sulokas'), ('sulosti'), ('sulotar'), ('suloton'),
('sulutus'), ('sumakki'), ('summata'), ('summaus'), ('summeri'), ('sumplia'), ('sumutin'), ('sumutus'), ('suojain'), ('suojata'),
('suojaus'), ('suojelu'), ('suolata'), ('suolaus'), ('suoltaa'), ('suoltua'), ('suopeus'), ('suoraan'), ('suoreta'), ('suorite'),
('suortua'), ('suoruus'), ('suosija'), ('suostua'), ('suotava'), ('supatus'), ('supista'), ('suppaus'), ('suppeus'), ('suppilo'),
('suppuun'), ('supukka'), ('supulla'), ('supulle'), ('supussa'), ('surfata'), ('surfaus'), ('surista'), ('surkeus'), ('surmata'),
('surrata'), ('suruton'), ('surutyö'), ('survoin'), ('susipuu'), ('sutkaus'), ('suttura'), ('suualue'), ('suudita'), ('suukopu'),
('suulake'), ('suulaki'), ('suulaus'), ('suunnin'), ('suuntia'), ('suupala'), ('suupuhe'), ('suureta'), ('suurima'), ('suurimo'),
('suurtyö'), ('suuruus'), ('suusola'), ('suutari'), ('suutelo'), ('suutelu'), ('suuttua'), ('suuvesi'), ('suvaita'), ('suvakki'),
('suvanto'), ('suvinen'), ('suvuton'), ('swahili'), ('svenski'), ('svetari'), ('sviitti'), ('syanidi'), ('sydämys'), ('sydänyö'),
('syfilis'), ('sykintä'), ('sykkyrä'), ('sykloni'), ('syleily'), ('sylfidi'), ('symboli'), ('sympata'), ('symppis'), ('synapsi'),
('synkata'), ('synketä'), ('synkeys'), ('syntymä'), ('syreeni'), ('syrjään'), ('syssyyn'), ('systeri'), ('sytkäri'), ('sytytin'),
('sytytys'), ('syvälle'), ('syvällä'), ('syvälti'), ('syvältä'), ('syvänkö'), ('syvänne'), ('syvässä'), ('syvästi'), ('syvästä'),
('syyhytä'), ('syyloma'), ('syynätä'), ('syynäys'), ('syysjää'), ('syyskuu'), ('syyttää'), ('syöksyä'), ('syömäri'), ('syönnös'),
('syöpymä'), ('syöttää'), ('syötävä'), ('syöveri'), ('syövyte'), ('sädease'), ('sädetin'), ('sädetys'), ('säestys'), ('säestää'),
('sähistä'), ('sähläri'), ('sählätä'), ('sähläys'), ('sähäkkä'), ('säihkyä'), ('säikkyä'), ('säikäys'), ('säilyke'), ('säilymä'),
('säilymö'), ('säilyte'), ('säilöte'), ('säkitys'), ('säkkärä'), ('säkätys'), ('sälytys'), ('sämpylä'), ('sännätä'), ('säpistä'),
('säpäkkä'), ('säristä'), ('särkijä'), ('särmätä'), ('särmäys'), ('säröily'), ('särötön'), ('säteily'), ('sävelmä'), ('sävyisä'),
('sävykäs'), ('sävytys'), ('sävytön'), ('säynävä'), ('säyseys'), ('säännös'), ('sääolot'), ('säästiö'), ('säästyä'), ('säästää'),
('säätely'), ('säätila'), ('säätäjä'), ('söhlätä'), ('sönkätä'), ('söpöily'), ('söpösti'), ('söpötys'), ('sörkkiä');

-- Words starting with T
INSERT INTO finnish_words(word) VALUES
('taaemma'), ('taaempi'), ('taajaan'), ('taajama'), ('taajeta'), ('taajuus'), ('taalari'), ('taaleri'), ('taammas'), ('taampaa'),
('taantua'), ('taapero'), ('taateli'), ('tabbule'), ('tadikko'), ('taemmas'), ('taempaa'), ('tahansa'), ('tahaton'), ('tahikka'),
('tahkota'), ('tahmata'), ('tahmeta'), ('tahmeus'), ('tahokas'), ('tahrata'), ('taikina'), ('taikuri'), ('taikuus'), ('taimata'),
('taimaus'), ('taimmas'), ('taimpaa'), ('taintua'), ('taionta'), ('taipale'), ('taipuma'), ('taipuva'), ('taitaja'), ('taitava'),
('taittaa'), ('taittua'), ('taituri'), ('tajunta'), ('tajuton'), ('takaaja'), ('takamaa'), ('takamus'), ('takaosa'), ('takaovi'),
('takapää'), ('takatie'), ('takauma'), ('takavyö'), ('taklata'), ('taklaus'), ('takotyö'), ('taksari'), ('talamus'), ('taleban'),
('taliban'), ('talikko'), ('talkita'), ('talkoot'), ('tallata'), ('tallaus'), ('tallete'), ('tallium'), ('talonki'), ('taloton'),
('taltata'), ('talteen'), ('talttua'), ('talutin'), ('talviyö'), ('tampata'), ('tamponi'), ('tanakka'), ('tanassa'), ('tangelo'),
('tanhuta'), ('tankata'), ('tankini'), ('tanssia'), ('tantere'), ('taoismi'), ('taottaa'), ('tapaama'), ('tapailu'), ('tapatus'),
('tapella'), ('tapetti'), ('tapiiri'), ('tapioka'), ('tapitus'), ('tappaja'), ('tappara'), ('tappelu'), ('tappura'), ('taputus'),
('tarakka'), ('tarhata'), ('tarhaus'), ('tarhuri'), ('tariffi'), ('tarjeta'), ('tarjona'), ('tarjota'), ('tarjous'), ('tarkata'),
('tarkoin'), ('tarokki'), ('tarpeen'), ('tarrain'), ('tarrata'), ('tarttua'), ('tarusto'), ('tarvike'), ('tarvita'), ('tasaaja'),
('tasaerä'), ('tasalla'), ('tasalle'), ('tasalta'), ('tasamaa'), ('tasanko'), ('tasanne'), ('tasapää'), ('tasassa'), ('tasasta'),
('tasetti'), ('tasinko'), ('tasoero'), ('tasoite'), ('tasokas'), ('tasokoe'), ('tasseli'), ('tasting'), ('tataari'), ('tattari'),
('tauoton'), ('tauotus'), ('taustaa'), ('tavailu'), ('tavaton'), ('taverna'), ('tavoite'), ('tavutus'), ('taxfree'), ('teelasi'),
('teelmys'), ('teemuki'), ('teettää'), ('teevati'), ('teevesi'), ('tehoisa'), ('tehokas'), ('tehoste'), ('tehoton'), ('tehotus'),
('tehtävä'), ('teikata'), ('teilata'), ('teilaus'), ('teipata'), ('tekarit'), ('tekojää'), ('tekokuu'), ('tekonen'), ('tekosyy'),
('tekoäly'), ('telakka'), ('telaluu'), ('telapuu'), ('telatie'), ('teleala'), ('teleksi'), ('teljetä'), ('telmätä'), ('temmata'),
('tempaus'), ('tempera'), ('tempura'), ('tenhota'), ('tennari'), ('tensidi'), ('tentata'), ('tenttiä'), ('teologi'), ('teosofi'),
('tequila'), ('terapia'), ('terassi'), ('teritys'), ('termari'), ('terrori'), ('tervata'), ('tervaus'), ('terveys'), ('teräase'),
('teräkäs'), ('teräste'), ('terästö'), ('testata'), ('testaus'), ('testeri'), ('tetanus'), ('tetsata'), ('teuhata'), ('teutoni'),
('tiainen'), ('tiedote'), ('tiejyrä'), ('tiekone'), ('tienata'), ('tietous'), ('tieturi'), ('tietäjä'), ('tietämä'), ('tietävä'),
('tiheään'), ('tihkuta'), ('tihutus'), ('tihutyö'), ('tiikeri'), ('tiineys'), ('tiirata'), ('tiistai'), ('tiiveys'), ('tiiviys'),
('tiketti'), ('tikkaat'), ('tikkari'), ('tikkaus'), ('tikkuri'), ('tilaaja'), ('tilanne'), ('tilasto'), ('tilaton'), ('tiliote'),
('tilitys'), ('tilkitä'), ('tiltata'), ('tilutus'), ('timjami'), ('timotei'), ('timperi'), ('timpuri'), ('tingata'), ('tinkaan'),
('tinneri'), ('tintata'), ('tipaton'), ('tippari'), ('tippuri'), ('tiputus'), ('tiristä'), ('tirskua'), ('tiskari'), ('tiskata'),
('tiskaus'), ('tislain'), ('tislata'), ('tislaus'), ('titaani'), ('titityy'), ('titrata'), ('titraus'), ('titteli'), ('titteri'),
('tiuheta'), ('tiukata'), ('tiuketa'), ('tiukkua'), ('tiuskia'), ('toccata'), ('todella'), ('todesta'), ('todesti'), ('todiste'),
('tohista'), ('tohjona'), ('tohtori'), ('tohveli'), ('toilaus'), ('toimari'), ('toimija'), ('toimite'), ('toimiva'), ('tointua'),
('toiseus'), ('toistaa'), ('toistin'), ('toistua'), ('tokaisu'), ('tokkura'), ('tolalla'), ('tolalle'), ('tolalta'), ('tolilla'),
('tolille'), ('tolilta'), ('tolvana'), ('tomutus'), ('tonikki'), ('toonika'), ('topaasi'), ('topakka'), ('topless'), ('toppari'),
('toppaus'), ('torailu'), ('toraisa'), ('torakka'), ('torjuva'), ('torkkua'), ('tornado'), ('tornari'), ('torpata'), ('torpedo'),
('torstai'), ('torvelo'), ('tosiaan'), ('tosikko'), ('totaali'), ('toteama'), ('toteemi'), ('totella'), ('toteuma'), ('totinen'),
('totoaja'), ('touhuta'), ('toutain'), ('transsi'), ('treffit'), ('tremolo'), ('trenssi'), ('triumfi'), ('troikka'), ('trokari'),
('trokata'), ('trokaus'), ('truismi'), ('truutta'), ('tsekata'), ('tsemppi'), ('tsinnia'), ('tsoukki'), ('tsunami'), ('tsätätä'),
('tuftata'), ('tuhista'), ('tuhkata'), ('tuhkaus'), ('tuhkelo'), ('tuhkimo'), ('tuhkuri'), ('tuhlari'), ('tuhlata'), ('tuhlaus'),
('tuhmuus'), ('tuhoaja'), ('tuhoisa'), ('tuhooja'), ('tuhoton'), ('tuhrata'), ('tuhutus'), ('tuikata'), ('tuikeus'), ('tuikkaa'),
('tuikkia'), ('tuimeta'), ('tuimuus'), ('tuiskia'), ('tukaani'), ('tukipuu'), ('tukityö'), ('tukkoon'), ('tukkuri'), ('tukossa'),
('tuliase'), ('tulikoe'), ('tulinen'), ('tulitus'), ('tulityö'), ('tulkata'), ('tulkita'), ('tullata'), ('tullaus'), ('tuloero'),
('tuloerä'), ('tulokas'), ('tuloste'), ('tulotie'), ('tuloton'), ('tulpata'), ('tulpita'), ('tumaton'), ('tummeta'), ('tumpata'),
('tumpelo'), ('tumpula'), ('tunnari'), ('tunneli'), ('tuntija'), ('tuntuma'), ('tunturi'), ('tuntuva'), ('tuohtua'), ('tuoksua'),
('tuomari'), ('tuomita'), ('tuonela'), ('tuoreus'), ('tuottaa'), ('tupakka'), ('tupakki'), ('tuparit'), ('tuplata'), ('tuppilo'),
('tupraus'), ('tupruta'), ('tuputus'), ('turhaan'), ('turhake'), ('turhuus'), ('turilas'), ('turismi'), ('turista'), ('turisti'),
('turjake'), ('turmelu'), ('turnaus'), ('turskua'), ('tursuta'), ('turvata'), ('turvota'), ('tussari'), ('tussata'), ('tussaus'),
('tutista'), ('tutkain'), ('tutkata'), ('tutkaus'), ('tutkija'), ('tutkiva'), ('tuttava'), ('tuttuus'), ('tutusti'), ('tuuheta'),
('tuultaa'), ('tuultua'), ('tuumata'), ('tuumaus'), ('tuumori'), ('tuunata'), ('tuunaus'), ('tuupata'), ('tuuppia'), ('tuurata'),
('tuutata'), ('tuutori'), ('tviitti'), ('twiitti'), ('tyhjetä'), ('tyhjiin'), ('tyhjyys'), ('tyhjätä'), ('tyhmetä'), ('tyhmyri'),
('tyhmyys'), ('tykisti'), ('tykistö'), ('tykitys'), ('tykytys'), ('tyllerö'), ('tylpetä'), ('tylsetä'), ('tylstyä'), ('tylsyys'),
('tylysti'), ('tylytys'), ('tympeys'), ('tymäkkä'), ('tynnyri'), ('typekäs'), ('typerys'), ('typetys'), ('typykkä'), ('tyranni'),
('tyrkkiä'), ('tyrkätä'), ('tyrmätä'), ('tyrmäys'), ('tyrskiä'), ('tyräkki'), ('tyssätä'), ('tyssäys'), ('tytistä'), ('tytteli'),
('tyttöys'), ('tyvekäs'), ('tyvipää'), ('tyydyke'), ('tyyneys'), ('tyyntyä'), ('tyystin'), ('tyytätä'), ('työaika'), ('työasia'),
('työehto'), ('työeste'), ('työhalu'), ('työinto'), ('työkalu'), ('työkone'), ('työkyky'), ('työlupa'), ('työläys'), ('työmies'),
('työminä'), ('työnilo'), ('työnimi'), ('työntyä'), ('työntää'), ('työnäky'), ('työohje'), ('työolot'), ('työpaja'), ('työpari'),
('työpuku'), ('työstää'), ('työtapa'), ('työtaso'), ('työteho'), ('työtila'), ('työtulo'), ('työtupa'), ('työvara'), ('työvire'),
('työväki'), ('tähdätä'), ('tähkylä'), ('tähteys'), ('tähtimö'), ('tähtäin'), ('tähtäys'), ('tähyily'), ('tälleen'), ('tällätä'),
('tällään'), ('tällöin'), ('tältään'), ('täpösen'), ('täristä'), ('tärkeys'), ('tärkätä'), ('tärppiä'), ('tärpätä'), ('tärskyä'),
('tärvätä'), ('tärytin'), ('tärytys'), ('täsmätä'), ('täsmäys'), ('täyteen'), ('täyteys'), ('täyttyä'), ('täyttää'), ('töhrijä'),
('töhrätä'), ('tökötti'), ('töllätä'), ('töltätä'), ('tölvätä'), ('tölväys'), ('tömistä'), ('tömäkkä'), ('tönäisy'), ('töppäys'),
('töpseli'), ('töpötys'), ('törkeys'), ('törkäkä'), ('törkkiä'), ('törkätä'), ('törmätä'), ('törmäys'), ('törsätä'), ('törsäys'),
('törölle'), ('töröllä'), ('törössä'), ('töröstä'), ('törösuu'), ('tötterö'), ('töydätä'), ('töykeys'), ('töykkiä'), ('töykätä'),
('töytäys'), ('töötätä');

-- Words starting with U
INSERT INTO finnish_words(word) VALUES
('ubiikki'), ('ufoilla'), ('ufologi'), ('ugristi'), ('uhkaaja'), ('uhkaava'), ('uhkailu'), ('uhmaikä'), ('uhmaisa'), ('uhmakas'),
('uhripuu'), ('uiguuri'), ('uikutus'), ('uinailu'), ('uistelu'), ('uitella'), ('ujellus'), ('ujeltaa'), ('ujoilla'), ('ujuttaa'),
('ukkoikä'), ('ukkonen'), ('ukottua'), ('ukraina'), ('ukulele'), ('ulahdus'), ('ulahtaa'), ('ulettua'), ('ulkoasu'), ('ulkoilu'),
('ulkomaa'), ('ulkonee'), ('ulkotyö'), ('ullakko'), ('uloinna'), ('ulommas'), ('ulompaa'), ('ulonnus'), ('ulontaa'), ('ulosajo'),
('ulostaa'), ('ulostus'), ('ulottaa'), ('ulottua'), ('ulpukka'), ('ulsteri'), ('ultrata'), ('ulvonta'), ('ummella'), ('ummessa'),
('ummetus'), ('ummikko'), ('umpijää'), ('umpiluu'), ('umpipuu'), ('umpitie'), ('umppari'), ('uneksia'), ('unelias'), ('unettaa'),
('uniikki'), ('unikeko'), ('unikuva'), ('unilelu'), ('unipesä'), ('unisuus'), ('unitila'), ('univaje'), ('unnutus'), ('unohdus'),
('unohtaa'), ('unohtua'), ('upeasti'), ('upottaa'), ('upouusi'), ('uppista'), ('uppoama'), ('uppopuu'), ('uppouma'), ('upseeri'),
('upsista'), ('urahdus'), ('urahtaa'), ('urautua'), ('urbaani'), ('urheilu'), ('urittaa'), ('urkinta'), ('urkkija'), ('urologi'),
('uroteko'), ('urpoilu'), ('urputus'), ('useasti'), ('uskomus'), ('uskonto'), ('uskoton'), ('uskottu'), ('usuttaa'), ('utelias'),
('utelija'), ('utuinen'), ('uumoilu'), ('uunipuu'), ('uupumus'), ('uusaste'), ('uusikuu'), ('uusinta'), ('uusinto'), ('uusjako'),
('uutimet'), ('uutinen'), ('uuttera'), ('uuvutus'), ('uzbekki');

-- Words starting with V
INSERT INTO finnish_words(word) VALUES
('vaaitus'), ('vaakita'), ('vaakkua'), ('vaakuna'), ('vaaleta'), ('vaaleus'), ('vaanija'), ('vaappua'), ('vaarain'), ('vaatija'),
('vaativa'), ('vadelma'), ('vaellus'), ('vaeltaa'), ('vahakas'), ('vahdata'), ('vahinko'), ('vahvari'), ('vahvero'), ('vahveta'),
('vahvike'), ('vahvuus'), ('vaihdin'), ('vaihdos'), ('vaihtaa'), ('vaihtua'), ('vaijeri'), ('vaikeus'), ('vaikkei'), ('vaikute'),
('vaimeta'), ('vaimoke'), ('vainaja'), ('vainota'), ('vainuta'), ('vaisuus'), ('vaivata'), ('vaivaus'), ('vaivero'), ('vaivoin'),
('vajakki'), ('vajoama'), ('vakaaja'), ('vakkari'), ('vakoilu'), ('vakooja'), ('vakuumi'), ('valaisu'), ('valakka'), ('valanta'),
('valeasu'), ('valella'), ('valelma'), ('valikko'), ('valinta'), ('valitus'), ('valjaat'), ('valjeta'), ('valjuus'), ('valkama'),
('valkata'), ('valkeus'), ('vallata'), ('vallita'), ('valloni'), ('valmius'), ('valoisa'), ('valopää'), ('valotus'), ('valtaan'),
('valtaus'), ('valtava'), ('valtias'), ('valtimo'), ('valtius'), ('valtoin'), ('valtuus'), ('valunta'), ('valutus'), ('valvoja'),
('valvomo'), ('valvuri'), ('valööri'), ('vampata'), ('vangita'), ('vanheta'), ('vanhuus'), ('vanikka'), ('vanilja'), ('vanketa'),
('vankeus'), ('vankila'), ('vannike'), ('vanukas'), ('vanutus'), ('vapista'), ('vappuyö'), ('varaaja'), ('varaamo'), ('varaani'),
('varakas'), ('varalla'), ('varalle'), ('varalta'), ('varanto'), ('varaosa'), ('varassa'), ('varasta'), ('varasto'), ('varatie'),
('varaton'), ('varauma'), ('varhain'), ('varikko'), ('varista'), ('variste'), ('varjagi'), ('varjelu'), ('varjota'), ('varkain'),
('varkaus'), ('varmaan'), ('varmeta'), ('varmuus'), ('varpata'), ('varrota'), ('vartalo'), ('varteen'), ('varteva'), ('vartija'),
('varttaa'), ('varttua'), ('varuste'), ('varvata'), ('vasalli'), ('vasikka'), ('vasiten'), ('vaskata'), ('vaskaus'), ('vasonta'),
('vastaan'), ('vastake'), ('vastata'), ('vastaus'), ('vastike'), ('vastine'), ('vastoin'), ('vatiini'), ('vatkain'), ('vatkata'),
('vatkaus'), ('vatkuli'), ('vatukka'), ('vatukko'), ('vauraus'), ('vauvala'), ('vauveli'), ('vavista'), ('vedekäs'), ('vedellä'),
('vedetön'), ('vedätys'), ('vegaani'), ('vehdata'), ('vehmaus'), ('vehreys'), ('vehtaus'), ('veijari'), ('veikata'), ('veikeys'),
('veisata'), ('veisaus'), ('veistos'), ('veistää'), ('veiterä'), ('veivata'), ('veivaus'), ('vekkari'), ('vekkaus'), ('vekkuli'),
('vekotin'), ('vekseli'), ('vektori'), ('velaton'), ('velinen'), ('veljeys'), ('veljyys'), ('velkoja'), ('veluuri'), ('vempain'),
('vempele'), ('venakko'), ('veneily'), ('venkoli'), ('venonen'), ('ventata'), ('venytys'), ('veranta'), ('verekäs'), ('veretön'),
('verhota'), ('verhous'), ('verikoe'), ('verinen'), ('verityö'), ('veriura'), ('verkilö'), ('veroale'), ('veroton'), ('verotus'),
('verrari'), ('verrata'), ('verroin'), ('verstas'), ('vertaus'), ('vertoja'), ('vesakko'), ('vesikko'), ('vesikoe'), ('vesinen'),
('vesipää'), ('vesistö'), ('vesitie'), ('vesitse'), ('vesitys'), ('vesivyö'), ('veskari'), ('vesseli'), ('vetelys'), ('vetimet'),
('vetinen'), ('vetoaja'), ('vetoapu'), ('vetoava'), ('vetoisa'), ('vetooja'), ('vetäisy'), ('veuhtoa'), ('vibrato'), ('viehkeä'),
('viehtyä'), ('viemäri'), ('vienous'), ('vieraus'), ('viereen'), ('vieremä'), ('viestin'), ('viestiä'), ('vieteri'), ('vietnam'),
('viettää'), ('vietävä'), ('vigilia'), ('vihaaja'), ('vihanta'), ('vihdoin'), ('viheriö'), ('vihervä'), ('vihille'), ('vihillä'),
('vihiltä'), ('vihjata'), ('vihjaus'), ('vihkijä'), ('vihreys'), ('vihtori'), ('vihvilä'), ('viihtyä'), ('viikari'), ('viikata'),
('viikate'), ('viikuna'), ('viilari'), ('viilata'), ('viilaus'), ('viileke'), ('viiletä'), ('viileys'), ('viillos'), ('viiltää'),
('viimein'), ('viineri'), ('viinuri'), ('viipale'), ('viipymä'), ('viirata'), ('viisari'), ('viisaus'), ('viistää'), ('viisumi'),
('viitata'), ('viitsiä'), ('viittoa'), ('viivain'), ('viivata'), ('viivaus'), ('vikapää'), ('vikistä'), ('vikkelä'), ('vilistä'),
('viljava'), ('viljely'), ('vilkaus'), ('vilkkaa'), ('vilkkua'), ('villava'), ('villeys'), ('villitä'), ('villiys'), ('vilpola'),
('vilukko'), ('vilunki'), ('vilutus'), ('vimpain'), ('vinkata'), ('vinkaus'), ('vinkeys'), ('vinoilu'), ('vinokas'), ('vinossa'),
('vinosti'), ('vinouma'), ('vintage'), ('vintata'), ('vintilä'), ('vinyyli'), ('vipajaa'), ('vipatus'), ('vipistä'), ('vippaus'),
('vipusin'), ('viraali'), ('virasto'), ('viraton'), ('viriili'), ('viritin'), ('viritys'), ('virkata'), ('virkeys'), ('virkkaa'),
('virkkuu'), ('virpoja'), ('virrata'), ('virtaus'), ('virttyä'), ('virutus'), ('virveli'), ('virvoke'), ('visailu'), ('visapuu'),
('visiiri'), ('viskari'), ('viskata'), ('viskely'), ('vislata'), ('vislaus'), ('vispata'), ('vispaus'), ('vispilä'), ('vissiin'),
('visusti'), ('vitaali'), ('vitkaan'), ('vitonen'), ('vitsaus'), ('vitusti'), ('vitutus'), ('viuhina'), ('viuhtoa'), ('vivahde'),
('vohveli'), ('voihkia'), ('voimala'), ('voisula'), ('voitava'), ('voitelu'), ('voittaa'), ('vokaali'), ('vokkaus'), ('voltata'),
('volyymi'), ('vongata'), ('vonkale'), ('vosikka'), ('voucher'), ('vouhake'), ('vuolaus'), ('vuorata'), ('vuoraus'), ('vyyhtiä'),
('vyöhyke'), ('vyörymä'), ('vyöttää'), ('vyötärö'), ('vähempi'), ('vähissä'), ('vähiten'), ('väikkyä'), ('väistin'), ('väistyä'),
('väistää'), ('väittää'), ('väkisin'), ('väkkärä'), ('väkänen'), ('välierä'), ('välikkö'), ('välille'), ('välillä'), ('väliltä'),
('välinen'), ('väliovi'), ('välissä'), ('välistä'), ('välitse'), ('välitys'), ('välityö'), ('välitön'), ('väljetä'), ('väljyys'),
('välkkyä'), ('välpätä'), ('välttyä'), ('välttää'), ('vängätä'), ('vänistä'), ('vänkäri'), ('väpätys'), ('väreily'), ('värikäs'),
('värinen'), ('väristä'), ('väritys'), ('väritön'), ('värjäri'), ('värjätä'), ('värjäys'), ('värkätä'), ('värväri'), ('värvätä'),
('värväys'), ('väskynä'), ('väsymys'), ('väsynyt'), ('väsytys'), ('väännin'), ('väännös'), ('vääntyä'), ('vääntää'), ('vääpeli'),
('väärtti'), ('vääryys');

-- Words starting with W
INSERT INTO finnish_words(word) VALUES
('western'), ('whippet'), ('whoopie'), ('wokkaus');

-- Words starting with X
-- No words

-- Words starting with Y
INSERT INTO finnish_words(word) VALUES
('ydinase'), ('ydinkoe'), ('ydinluu'), ('ydinosa'), ('ydinpuu'), ('yhdelmä'), ('yhdessä'), ('yhdesti'), ('yhdiste'), ('yhdyntä'),
('yhteisö'), ('yhtikäs'), ('yhyttää'), ('ykkönen'), ('yksikkö'), ('yksissä'), ('yksönen'), ('yleensä'), ('yleinen'), ('ylemmäs'),
('ylempää'), ('ylennys'), ('ylentyä'), ('ylentää'), ('ylettyä'), ('ylettää'), ('ylevyys'), ('ylhäisö'), ('yliaika'), ('ylimeno'),
('yliminä'), ('ylimmäs'), ('ylisana'), ('ylispuu'), ('ylistys'), ('ylistää'), ('ylittyä'), ('ylittää'), ('yliveto'), ('yllytin'),
('yllytys'), ('ylläkkö'), ('yllätys'), ('ylpeily'), ('yläaste'), ('yläilma'), ('ylämäki'), ('yläoksa'), ('yläpeti'), ('yläraja'),
('ylärivi'), ('ymmälle'), ('ymmällä'), ('ymppäys'), ('ympärys'), ('ynähdys'), ('ynähtää'), ('ypsilon'), ('yrittää'), ('yskintä'),
('yskäisy'), ('yöastia'), ('yöbaari'), ('yöeläin'), ('yöelämä'), ('yökaste'), ('yökausi'), ('yökerho'), ('yökkäys'), ('yökylmä'),
('yölento'), ('yölintu'), ('yömaito'), ('yömyssy'), ('yömyöhä'), ('yöpaita'), ('yöpilvi'), ('yöpimeä'), ('yöpuoli'), ('yöpöytä'),
('yöradio'), ('yörauha'), ('yösydän'), ('yösähkö'), ('yösäilö'), ('yötaksa'), ('yötuuli'), ('yövaate'), ('yövahti'), ('yövoide'),
('yövuoro'), ('yövyntä');

-- Words starting with Z
INSERT INTO finnish_words(word) VALUES
('zakuska'), ('zirkoni'), ('zoologi'), ('zoomata'), ('zoomaus');

-- Words starting with Å
-- No words

-- Words starting with Ä
INSERT INTO finnish_words(word) VALUES
('ähellys'), ('äheltää'), ('ähkäisy'), ('ähäpiti'), ('äiditön'), ('äijäily'), ('äkeillä'), ('äkeästi'), ('äkimmin'), ('äksiisi'), 
('äksyily'), ('äksysti'), ('äkäillä'), ('äkäinen'), ('ällötys'), ('älypeli'), ('älysiru'), ('älytalo'), ('älyttää'), ('älähdys'), 
('älähtää'), ('älämölö'), ('ängelmä'), ('änkytys'), ('äreästi'), ('ärhäkkä'), ('ärhäkäs'), ('ärjyntä'), ('ärjäisy'), ('ärräpää'), 
('ärsytys'), ('ärtyisä'), ('ärtymys'), ('ärähdys'), ('ärähtää'), ('ätläkkä'), ('äveriäs'), ('äyskäri'), ('äänekäs'), ('äänetön'), 
('ääniala'), ('ääninen'), ('äänipää'), ('äänitys'), ('ääntely'), ('äärelle'), ('äärellä'), ('ääreltä'), ('ääressä'), ('äärestä'), 
('ääretön'), ('ääriosa'), ('ääripää');

-- Words starting with Ö
INSERT INTO finnish_words(word) VALUES
('ökyillä'), ('ökytalo'), ('öljymaa'), ('öljypuu'), ('örähdys'), ('örähtää'), ('öykkäri'), ('öylätti');