export const colorPaletteConstants = {
  PRIMARY_COLOR_0: 0,
  SECONDARY_COLOR_1: 1,
  TERTIARY_COLOR_2: 2,
  CORRECT_GREEN_3: 3,
  INCORRECT_RED_4: 4,
  DUPLICATE_BLUE_5: 5,
};

export const gameConstants = {
  WORD_LENGTH_4: 4,
  WORD_LENGTH_5: 5,
  WORD_LENGTH_6: 6,
  WORD_LENGTH_7: 7,
  WORD_COUNT_5: 5,
};

export const languageConstants = {
  FI: "fi",
};

export const stylingConstants = {
  COLOR_SCHEME_LIGHT: "light",
  COLOR_SCHEME_DARK: "dark",
  SM_VIEWPORT_MAX_WIDTH: "(max-width: 48em)",
  ICON_STROKE_WIDTH: 2,
  BORDER_WIDTH: 2,
  HEADER_MARGIN_TOP: "2vh",
  HEADER_MARGIN_BOTTOM: "3vh",
  HEADER_TITLE_FONT_SIZE_SMALL: "2rem",
  HEADER_TITLE_FONT_SIZE_LARGE: "4rem",
  HEADER_ICON_SIZE_SMALL: "1.5rem",
  HEADER_ICON_SIZE_LARGE: "3rem",
  TEXT_INPUT_SIZE_SMALL: "2.75rem",
  TEXT_INPUT_SIZE_LARGE: "5.5rem",
  TEXT_INPUT_FONT_SIZE_SMALL: "1rem",
  TEXT_INPUT_FONT_SIZE_LARGE: "2rem",
  ROW_VALIDATION_ICON_SIZE_SMALL: "1rem",
  ROW_VALIDATION_ICON_SIZE_LARGE: "2rem",
  ROW_VALIDATION_ICON_OFFSET_SMALL: "-1.25rem",
  ROW_VALIDATION_ICON_OFFSET_LARGE: "-2.5rem",
  MODAL_TITLE_FONT_SIZE: "1.5rem",
  MODAL_TEXT_MARGIN_TOP: "1rem",
  MODAL_TEXT_MARGIN_BOTTOM: "1rem",
  MODAL_DIVIDER_MARGIN_TOP: "1rem",
  MODAL_DIVIDER_MARGIN_BOTTOM: "1rem",
  MODAL_ICON_SIZE: "3rem",
  MODAL_ICON_MARGIN_TOP: "0.25rem",
  MODAL_ICON_MARGIN_BOTTOM: "0.25rem",
  MODAL_BUTTON_MARGN_TOP: "1rem",
};
