export const colorPaletteConstants = {
  PRIMARY_COLOR_0: 0,
  SECONDARY_COLOR_1: 1,
  TERTIARY_COLOR_2: 2,
  CORRECT_GREEN_3: 3,
  INCORRECT_RED_4: 4,
  DUPLICATE_BLUE_5: 5,
};

export const gameConstants = {
  WORD_LENGTH_4: 4,
  WORD_LENGTH_5: 5,
  WORD_LENGTH_6: 6,
  WORD_LENGTH_7: 7,
  WORD_COUNT_5: 5,
};

export const languageConstants = {
  FI: "fi",
};

export const stylingConstants = {
  ICON_STROKE_WIDTH: 2,
  BORDER_WIDTH: 2,
  COLOR_SCHEME_LIGHT: "light",
  COLOR_SCHEME_DARK: "dark",
  MODAL_TITLE_FONT_SIZE: 24,
  MODAL_TEXT_MARGIN_TOP: 10,
  MODAL_TEXT_MARGIN_BOTTOM: 10,
  MODAL_DIVIDER_MARGIN_TOP: 20,
  MODAL_DIVIDER_MARGIN_BOTTOM: 20,
  MODAL_ICON_SIZE: 35,
  MODAL_ICON_MARGIN_TOP: 5,
  MODAL_ICON_MARGIN_BOTTOM: 5,
  MODAL_BUTTON_MARGN_TOP: 10,
  HEADER_MARGIN_TOP: 20,
  HEADER_MARGIN_BOTTOM: 20,
};
