spring:
  application:
    name: backend
  datasource:
    # SQLite DB path configurable via SQLITE_DB_PATH environment variable
    url: jdbc:sqlite:${SQLITE_DB_PATH}
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  port: 8080

CorsAllowedOrigin: ${CORS_ALLOWED_ORIGIN}