spring:
  application:
    name: backend
  datasource:
    url: jdbc:sqlite:/workdir/database/database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  port: 8080

CorsAllowedOrigin: http://localhost:5173