spring:

  application:
    name: backend

  server:
    address: 0.0.0.0

  datasource:
    # SQLite DB path configurable via SQLITE_DB_PATH environment variable
    url: jdbc:sqlite:${SQLITE_DB_PATH:/database/database.db}
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s

# Cors allowed origin from compose
CorsAllowedOrigin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}