spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    # Datasource variables come from compose.yaml or from GitHub secrets
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: [classpath:finnishWords/finnish-*-letter-words.sql]

CorsAllowedOrigin: ${CORS_ALLOWED_ORIGIN}