spring:

  application:
    name: backend

  server:
    address: 0.0.0.0
    
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:/database/database.db}
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

# Cors allowed origin from compose
CorsAllowedOrigin: ${CORS_ALLOWED_ORIGIN}