name: CD / Create new version tag
description: Creates a new version tag based on merged PR update label and current semver version

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  get-version-number-from-latest-tag:
    name: Get version number from latest tag
    runs-on: ubuntu-latest
    # Runs only if PR was merged to main
    if: ${{ github.event.pull_request.merged == true }}
    outputs:
      current_version_number: ${{ steps.get-version-number-from-latest-tag.outputs.version_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version number from latest tag
        id: get-version-number-from-latest-tag 
        run: |
          git fetch origin --tags
          LATEST_TAG="$(git tag --list 'v*' --sort=-version:refname | head -n1)"

          if [ -z "$LATEST_TAG" ]; then
            echo "Error: No tags matching 'v*' were found in the repository" >&2
            exit 1
          fi

          echo "VERSION_NUMBER=${LATEST_TAG#v}" >> $GITHUB_OUTPUT

  get-pr-update-label:
    name: Get PR update label
    runs-on: ubuntu-latest
    # Runs only if PR was merged to main
    if: ${{ github.event.pull_request.merged == true }}
    outputs:
      pr_update_label: ${{ steps.get-pr-update-label.outputs.update_label }}

    steps:
      - name: Get PR update label
        id: get-pr-update-label
        uses: actions/github-script@v8
        with:
          script: |
            const prLabels = context.payload.pull_request.labels.map(label => label.name);
            let updateLabel;

            if (prLabels.includes('major update')) {
              updateLabel = 'major update';
            } else if (prLabels.includes('minor update')) {
              updateLabel = 'minor update';
            } else {
              updateLabel = 'patch update';
            }
            
            core.setOutput('update_label', updateLabel);

  create-new-version-number:
    name: Create a new version number
    runs-on: ubuntu-latest
    needs: [get-version-number-from-latest-tag, get-pr-update-label]
    env:
      CURRENT_VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.current_version_number }}
      PR_UPDATE_LABEL: ${{ needs.get-pr-update-label.outputs.pr_update_label }}
    outputs:
      new_version_number: ${{ steps.create-new-version-number.outputs.new_version_number }}

    steps:
      - name: Create a new version number
        id: create-new-version-number
        uses: actions/github-script@v8
        with:
          script: |
            const currentVersionNumber = process.env.CURRENT_VERSION_NUMBER;
            const updateLabel =  process.env.PR_UPDATE_LABEL;

            let majorVersion = parseInt(currentVersionNumber.split(".")[0]);
            let minorVersion = parseInt(currentVersionNumber.split(".")[1]);
            let patchVersion = parseInt(currentVersionNumber.split(".")[2]);

            if (updateLabel === 'major update') {
              majorVersion += 1;
              minorVersion = 0;
              patchVersion = 0;
            } else if (updateLabel === 'minor update') {
              minorVersion += 1;
              patchVersion = 0;
            } else if (updateLabel === 'patch update') {
              patchVersion += 1;
            } else {
              throw new Error("PR update label does not match 'major update', 'minor update' or 'patch update'");
            }

            const newVersionNumber = `${majorVersion}.${minorVersion}.${patchVersion}`;

            // Original semver regular expression from https://semver.org/ - modified expression here for JS
            const semVerRegEx = /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/;

            if (!semVerRegEx.test(newVersionNumber)) {
              throw new Error("New version number does not follow semantic versioning");
            }

            core.setOutput('new_version_number', newVersionNumber);

  create-new-tag:
    name: Create a new tag
    runs-on: ubuntu-latest
    needs: create-new-version-number
    env:
      NEW_VERSION_NUMBER: ${{ needs.create-new-version-number.outputs.new_version_number }}
    outputs:
      new_tag: ${{ steps.create-new-tag.outputs.new_tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create a new tag
        id: create-new-tag
        run: |
          NEW_TAG=v${NEW_VERSION_NUMBER}

          git switch main
          git pull origin main
          git tag ${NEW_TAG}
          git push origin ${NEW_TAG}

          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_OUTPUT

  trigger-deployment-workflow:
    name: Trigger deployment workflow
    runs-on: ubuntu-latest
    needs: create-new-tag
    env:
      NEW_TAG: ${{ needs.create-new-tag.outputs.new_tag }}
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Trigger deployment workflow
        run: |
          gh workflow run cd-deploy-to-azure.yaml --ref ${NEW_TAG}