name: CD / Deploy to Azure
description: Runs Azure deployments with latest pushed tag

on:
  # Only workflow_dispatch trigger because cd-update-version.yaml creates a workflow_dispatch event for this workflow
  # Deployment workflow should only be run
  # - automatically after successful tag creation
  # - manually from an existing tag
  workflow_dispatch:

jobs:
  get-version-number-from-latest-tag:
    name: Get version number from latest tag
    runs-on: ubuntu-latest
    outputs:
        version_number: ${{ steps.version_number.outputs.VERSION_NUMBER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Get version number from latest tag
      id: version_number
      run: |
        # Ref automatically set when triggered by workflow
        # Must be manually selected in GitHub when triggered manually
        LATEST_TAG=${{ github.ref_name }}

        # Original semver regular expression from https://semver.org/ - modified expression here
        SEMVER_REGEX="^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"

        if [[ ! ${LATEST_TAG} =~ ${SEMVER_REGEX} ]]; then
          echo "Tag is not valid"
          exit 1
        fi

        echo "VERSION_NUMBER=${LATEST_TAG#v}" >> $GITHUB_OUTPUT

  check-acr-images:
    name: Check ACR images
    runs-on: ubuntu-latest
    needs: get-version-number-from-latest-tag
    outputs:
      backend_image_in_acr: ${{ steps.check-acr-image-tags.outputs.backend_image_in_acr }}
      frontend_image_in_acr: ${{ steps.check-acr-image-tags.outputs.frontend_image_in_acr }}
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}

    steps:
    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check ACR image tags
      id: check-acr-image-tags
      run: |
        if az acr repository show-tags --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} --repository sanaboksi-backend --output tsv | grep -qFx ${{ env.VERSION_NUMBER }}; then
          echo "BACKEND_IMAGE_IN_ACR=true" >> $GITHUB_OUTPUT
        else
          echo "BACKEND_IMAGE_IN_ACR=false" >> $GITHUB_OUTPUT
        fi

        if az acr repository show-tags --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} --repository sanaboksi-frontend --output tsv | grep -qFx ${{ env.VERSION_NUMBER }}; then
          echo "FRONTEND_IMAGE_IN_ACR=true" >> $GITHUB_OUTPUT
        else
          echo "FRONTEND_IMAGE_IN_ACR=false" >> $GITHUB_OUTPUT
        fi

  build-and-deploy-backend-container-to-azure:
    name: Build and deploy backend container to Azure
    runs-on: ubuntu-latest
    # Needs job to make sure the correct tag is used for images
    needs: [get-version-number-from-latest-tag, check-acr-images]
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy existing backend container
      uses: azure/container-apps-deploy-action@v2
      if: ${{ needs.check-acr-images.outputs.backend_image_in_acr == 'true' }}
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-backend:${{ env.VERSION_NUMBER }}
        containerAppName: sanaboksi-backend

    - name: Build and deploy new backend container
      uses: azure/container-apps-deploy-action@v2
      if: ${{ needs.check-acr-images.outputs.backend_image_in_acr == 'false' }}
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        dockerfilePath: Dockerfile
        appSourcePath: ${{ github.workspace }}/backend
        imageToBuild: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-backend:${{ env.VERSION_NUMBER }}
        containerAppName: sanaboksi-backend
        environmentVariables: CORS_ALLOWED_ORIGIN=https://sanaboksi.fi
        ingress: external
        targetPort: 8080
        disableTelemetry: true

  build-and-deploy-frontend-container-to-azure:
    name: Build and deploy frontend container to Azure
    runs-on: ubuntu-latest
    # Needs jobs to make sure the correct tag is used for images and that backend is deployed
    needs: [get-version-number-from-latest-tag, check-acr-images, build-and-deploy-backend-container-to-azure]
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy existing frontend container
      uses: azure/container-apps-deploy-action@v2
      if: ${{ needs.check-acr-images.outputs.frontend_image_in_acr == 'true' }}
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-frontend:${{ env.VERSION_NUMBER }}
        containerAppName: sanaboksi-frontend

    - name: Build and deploy new frontend container
      uses: azure/container-apps-deploy-action@v2
      if: ${{ needs.check-acr-images.outputs.frontend_image_in_acr == 'false' }}
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        dockerfilePath: Dockerfile
        appSourcePath: ${{ github.workspace }}/frontend
        imageToBuild: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-frontend:${{ env.VERSION_NUMBER }}
        containerAppName: sanaboksi-frontend
        buildArguments: VITE_SERVER_URL=${{ secrets.AZURE_BACKEND_URL }}
        ingress: external
        targetPort: 80
        disableTelemetry: true