name: CD / Deploy to Azure
description: Runs Azure deployments with latest pushed tag

on:
  # Only workflow_dispatch trigger because cd-update-version.yaml creates a workflow_dispatch event for this workflow
  # Deployment workflow should only be run
  # - automatically after successful version update and tag creation
  # - manually from an existing tag
  workflow_dispatch:

jobs:
  get-version-number-from-latest-tag:
    name: Get version number from latest tag
    runs-on: ubuntu-latest
    outputs:
        version_number: ${{ steps.get_version_number_from_latest_tag.outputs.VERSION_NUMBER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Get version number from latest tag
      id: get_version_number_from_latest_tag
      run: |
        # Ref automatically set when triggered by workflow
        # Must be manually selected in GitHub when triggered manually
        REF_NAME=${{ github.ref_name }}

        # Original semver regular expression from https://semver.org/ - modified expression here
        SEMVER_REGEX="^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"

        if [[ ! ${REF_NAME} =~ ${SEMVER_REGEX} ]]; then
          echo "Ref is not a valid tag"
          exit 1
        else
          LATEST_TAG=${{ github.ref_name }}
        fi

        echo "VERSION_NUMBER=${LATEST_TAG#v}" >> $GITHUB_OUTPUT

  build-and-deploy-backend-container-to-azure:
    name: Build and deploy backend container to Azure
    runs-on: ubuntu-latest
    # Needs job to make sure the correct tag is used for images
    needs: get-version-number-from-latest-tag
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy backend container
      uses: azure/container-apps-deploy-action@v2
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        dockerfilePath: Dockerfile
        appSourcePath: ${{ github.workspace }}/backend
        imageToBuild: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-backend:${{ env.VERSION_NUMBER }}
        containerAppName: sanaboksi-backend
        environmentVariables: CORS_ALLOWED_ORIGIN=https://sanaboksi.fi
        ingress: external
        targetPort: 8080
        disableTelemetry: true

  build-and-deploy-frontend-container-to-azure:
    name: Build and deploy frontend container to Azure
    runs-on: ubuntu-latest
    # Needs jobs to make sure the correct tag is used for images and that backend is deployed
    needs: [get-version-number-from-latest-tag, build-and-deploy-backend-container-to-azure]
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy frontend container
      uses: azure/container-apps-deploy-action@v2
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        dockerfilePath: Dockerfile
        appSourcePath: ${{ github.workspace }}/frontend
        imageToBuild: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-frontend:${{ env.VERSION_NUMBER }}
        containerAppName: sanaboksi-frontend
        buildArguments: VITE_SERVER_URL=${{ secrets.AZURE_BACKEND_URL }}
        ingress: external
        targetPort: 80
        disableTelemetry: true