name: CI / Run backend and frontend checks
description: Runs formatting and linting checks as well as unit, integration and end-to-end tests on PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-backend-formatting-check:
    name: BE formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment

      - name: Run BE formatting check 
        run: cd backend && ./gradlew spotlessCheck

  run-frontend-formatting-check:
    name: FE formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE formatting check
        run: cd frontend && npx prettier . --check

  run-frontend-linting-check:
    name: FE linting check
    runs-on: ubuntu-latest
    needs: run-frontend-formatting-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE linting check
        run: cd frontend && npx eslint .

  run-backend-unit-tests:
    name: BE unit tests
    runs-on: ubuntu-latest
    needs: run-backend-formatting-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Build backend test image
        run: docker build -t sanaboksi-backend-test -f ./backend/Dockerfile.dev ./backend

      - name: Run BE unit tests in container
        run: |
          mkdir -p "${{ github.workspace }}/backend/build/reports/tests"
          docker run --rm --name be-unit-tests \
          -v "${{ github.workspace }}/backend/build/reports/tests:/workdir/build/reports/tests" \
          sanaboksi-backend-test sh -c "./gradlew --no-daemon unitTest"

      - name: Upload unit test report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: unit-test-report
          path: backend/build/reports/tests/unitTest/
  
  run-backend-integration-tests:
    name: BE integration tests
    runs-on: ubuntu-latest
    needs: run-backend-unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build backend test image
        run: docker build -t sanaboksi-backend-test -f ./backend/Dockerfile.dev ./backend

      - name: Run BE integration tests in container
        env:
          CORS_ALLOWED_ORIGIN: http://localhost:5173
          SQLITE_DB_PATH: /database/database.db
        run: |
          mkdir -p "${{ github.workspace }}/backend/build/reports/tests"
          docker run --rm --name be-integration-tests \
            -e CORS_ALLOWED_ORIGIN="${CORS_ALLOWED_ORIGIN}" -e SQLITE_DB_PATH="${SQLITE_DB_PATH}" \
            -v "${{ github.workspace }}/backend/build/reports/tests:/workdir/build/reports/tests" \
            sanaboksi-backend-test \
            sh -c "./databaseInit/reseed_database.sh && ./gradlew --no-daemon integrationTest"

      - name: Upload integration test report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: integration-test-report
          path: backend/build/reports/tests/integrationTest/

  run-end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    needs: [run-frontend-linting-check, run-backend-integration-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Install Playwright Browsers
        run: cd frontend && npx playwright install --with-deps

      - name: Build Docker containers
        run: docker compose -f compose.yaml up --build -d
        env:
          CORS_ALLOWED_ORIGIN: http://localhost:5173
          VITE_SERVER_URL: http://localhost:8080
    
      - name: Show backend logs on container build failure
        if: ${{ failure() }}
        run: docker logs sanaboksi_backend

      - name: Show frontend logs on container build failure
        if: ${{ failure() }}
        run: docker logs sanaboksi_frontend

      - name: Wait for frontend to be ready
        run: until curl --output /dev/null --silent --head --fail http://localhost:5173; do sleep 5; done

      - name: Run end-to-end tests
        run: cd frontend && npx playwright test

      - name: Upload Playwright report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report
          path: frontend/test-results/