name: CI / Run backend and frontend checks
description: Runs formatting and linting checks as well as unit, integration and end-to-end tests on feature PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-backend-formatting-check:
    name: BE formatting check
    runs-on: ubuntu-latest
    # Run checks only on feature PRs, not on PRs that update version
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'update/update-version-to-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment

      - name: Run BE formatting check
        run: |
          cd backend
          ./gradlew spotlessCheck
  
  run-frontend-formatting-check:
    name: FE formatting check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'update/update-version-to-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE formatting check
        run: |
          cd frontend
          npx prettier . --check

  run-frontend-linting-check:
    name: FE linting check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'update/update-version-to-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE linting check
        run: |
          cd frontend
          npx eslint .

  run-backend-unit-tests:
    name: BE unit tests
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'update/update-version-to-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment
      
      - name: Run BE unit tests
        run: |
          cd backend
          ./gradlew unitTest

      - name: Upload unit test report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: unit-test-report
          path: backend/build/reports/tests/unitTest/
  
  run-backend-integration-tests:
    name: BE integration tests
    env:
      SQLITE_DB_PATH: ./database/database.db
      CORS_ALLOWED_ORIGIN: http://localhost:5173
    runs-on: ubuntu-latest
    needs: run-backend-unit-tests
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'update/update-version-to-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment

      - name: Install SQLite3 for integration tests
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends sqlite3

      - name: Seed database
        env:
          DATABASE_DIRECTORY: ${{ github.workspace }}/backend/src/main/resources/database
        run: |
          cd backend/src/main/resources/databaseInit
          chmod +x ./reseed_database.sh
          ./reseed_database.sh
      
      - name: Run BE integration tests
        run: |
          cd backend
          ./gradlew integrationTest

      - name: Upload integration test report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: integration-test-report
          path: backend/build/reports/tests/integrationTest/

  run-end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    needs: run-backend-integration-tests
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'update/update-version-to-') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Build Docker containers
        run: docker compose -f compose.yaml up --build -d
        env:
          CORS_ALLOWED_ORIGIN: http://localhost:5173
          VITE_SERVER_URL: http://localhost:8080
    
      - name: Show backend logs on container build failure
        if: ${{ failure() }}
        run: docker logs sanaboksi_backend

      - name: Show frontend logs on container build failure
        if: ${{ failure() }}
        run: docker logs sanaboksi_frontend

      - name: Wait for frontend to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:5173; do sleep 5; done

      - name: Run end-to-end tests
        run: |
          cd frontend
          npx playwright test

      - name: Upload Playwright report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report
          path: frontend/test-results/