name: Continuous Integration (CI)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-backend-formatting-check:
    name: BE formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment

      - name: Run BE formatting check
        run: |
          cd backend
          ./gradlew spotlessCheck
  
  run-frontend-formatting-check:
    name: FE formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE formatting check
        run: |
          cd frontend
          npx prettier . --check

  run-frontend-linting-check:
    name: FE linting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE linting check
        run: |
          cd frontend
          npx eslint .

  run-backend-unit-tests:
    name: BE unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment
      
      - name: Run BE unit tests
        run: |
          cd backend
          ./gradlew unitTest
  
  run-backend-integration-tests:
    name: BE integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment
      
      - name: Run BE integration tests
        run: |
          cd backend
          ./gradlew integrationTest