name: Continuous Deployment (CD)

on:
  # Only workflow_dispatch trigger because update-version.yaml creates a workflow_dispatch event for this workflow
  # Deployment workflow should only be run after successful version update and tag creation
  workflow_dispatch:

jobs:
  get-version-number-from-latest-tag:
    name: Get version number from latest tag
    runs-on: ubuntu-latest
    outputs:
        version_number: ${{ steps.version_number.outputs.VERSION_NUMBER }}

    steps:
    - name: Get version number from latest tag
      id: version_number
      run: |
        # Name of the branch/tag that triggered the workflow, tag in this case
        LATEST_TAG=${{ github.ref_name }}
        echo "VERSION_NUMBER=${LATEST_TAG#v}" >> $GITHUB_OUTPUT

  build-and-deploy-backend-container-to-azure:
    name: Build and deploy backend container to Azure
    runs-on: ubuntu-latest
    needs: get-version-number-from-latest-tag
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy backend container
      uses: azure/container-apps-deploy-action@v2
      with:
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME}}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        dockerfilePath: Dockerfile
        appSourcePath: ${{ github.workspace }}/backend
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        imageToBuild: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-backend:${{ env.VERSION_NUMBER }}
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        containerAppName: sanaboksi-backend
        ingress: external
        targetPort: 8080
        disableTelemetry: true

  build-and-deploy-frontend-container-to-azure:
    name: Build and deploy frontend container to Azure
    runs-on: ubuntu-latest
    # Needs jobs to make sure the correct tag is used for images and that backend is deployed
    needs: [get-version-number-from-latest-tag, build-and-deploy-backend-container-to-azure]
    env:
      VERSION_NUMBER: ${{ needs.get-version-number-from-latest-tag.outputs.version_number }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy frontend container
      uses: azure/container-apps-deploy-action@v2
      with:
        acrUsername: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        dockerfilePath: Dockerfile
        appSourcePath: ${{ github.workspace }}/frontend
        acrName: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        imageToBuild: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sanaboksi-frontend:${{ env.VERSION_NUMBER }}
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APPS_ENVIRONMENT }}
        containerAppName: sanaboksi-frontend
        buildArguments: VITE_SERVER_URL=${{ secrets.AZURE_BACKEND_URL }}
        ingress: external
        targetPort: 80
        disableTelemetry: true