name: Continuous Integration (CI)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-backend-formatting-check:
    name: BE formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment

      - name: Run BE formatting check
        run: |
          cd backend
          ./gradlew spotlessCheck
  
  run-frontend-formatting-check:
    name: FE formatting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE formatting check
        run: |
          cd frontend
          npx prettier . --check

  run-frontend-linting-check:
    name: FE linting check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up frontend workflow environment
        uses: ./.github/actions/setup-frontend-workflow-environment

      - name: Run FE linting check
        run: |
          cd frontend
          npx eslint .

  run-backend-unit-tests:
    name: BE unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment
      
      - name: Run BE unit tests
        run: |
          cd backend
          ./gradlew unitTest

      - name: Upload unit test report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: unit-test-report
          path: backend/build/reports/tests/unitTest/
  
  run-backend-integration-tests:
    name: BE integration tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ vars.DATABASE_NAME }}
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up backend workflow environment
        uses: ./.github/actions/setup-backend-workflow-environment
      
      - name: Run BE integration tests
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          CORS_ALLOWED_ORIGIN: ${{ secrets.CORS_ALLOWED_ORIGIN }}
        run: |
          cd backend
          ./gradlew integrationTest

      - name: Upload integration test report on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: integration-test-report
          path: backend/build/reports/tests/integrationTest/